<a href="https://colab.research.google.com/github/enzoalvino00/Analitica-Empresarial-Integrada/blob/main/Unidad_1_Valor_del_dato/Semana_01_Empresa_analitica/Lab_D1/Analitica_Empresarial_Integrada_Lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# 🏛️ **TECSUP 2026-II  -  ANALÍTICA EMPRESARIAL INTEGRADA**
## 🔬 **LABORATORIO DIRIGIDO N.° 04** : **Analítica Diagnóstica: ¿Por Qué Pasó?**


| | |
|---|---|
| **Docente** | Pilar Rocío Sayán Mejía |
| **Laboratorio** | Diagnóstico de madurez analítica de una agroexportadora peruana |
| **N.° de laboratorio** |  4 |
| **Tema** | La Empresa Analítica en la Era de la IA |
| **Plan curricular** | Big Data y Ciencia de Datos · Código C28 · 2026-I |
| **Duración** | 200 minutos (6:50 p.m. – 10:10 p.m., con receso de 15 minutos) |
| **Modalidad** | Grupal. Las respuestas del foro son individuales. |

---

**Estudiante:** _Enzo Gabriel ALvino Carhuaricra_ &nbsp;&nbsp;&nbsp; **Sección:** __6C28__ &nbsp;&nbsp;&nbsp; **Fecha:** 09/09/2026

## Cuadro maestro de resultados

Este cuadro reúne, en una sola vista, todas las cifras que el laboratorio produce. Sirve al docente como referencia rápida durante la sesión y permite verificar de inmediato si un equipo se desvió en alguna regla de calidad. **Ninguna de estas cifras debe entregarse al estudiante antes de la ejecución**: el valor formativo del laboratorio está en que las obtenga por sí mismo.

### A. Calidad del dato

| Indicador | Valor | % del total |
|---|---:|---:|
| Filas totales del archivo original | 1 067 371 | 100.00 % |
| Filas duplicadas exactas | 34 335 | 3.22 % |
| Cancelaciones (factura con prefijo `C`) | 19 494 | 1.83 % |
| Cantidad ≤ 0 | 22 950 | 2.15 % |
| Precio ≤ 0 | 6 207 | 0.58 % |
| Cliente sin identificar | 243 007 | 22.77 % |
| Servicios y ajustes (no son producto) | 5 932 | 0.56 % |
| **Filas válidas tras las cuatro reglas** | **1 003 340** | **94.00 %** |
| Filas descartadas | 64 031 | 6.00 % |
| Filas fuera de los dos periodos (dic-2011 truncado) | 24 753 | — |
| **Filas comparables (P0 + P1)** | **978 587** | — |

### B. Comparación descriptiva de los dos periodos

P0 = diciembre 2009 – noviembre 2010 · P1 = diciembre 2010 – noviembre 2011

| Indicador | P0 | P1 | Variación | % |
|---|---:|---:|---:|---:|
| Ingresos (£) | 9 396 642 | 9 632 728 | +236 086 | **+2.51 %** |
| Unidades | 5 626 660 | 5 248 737 | −377 923 | **−6.72 %** |
| Facturas | 19 743 | 18 957 | −786 | −3.98 % |
| Clientes identificados | 4 240 | 4 294 | +54 | +1.27 % |
| Productos distintos | 4 220 | 3 904 | −316 | −7.49 % |
| Ticket promedio (£) | 475.95 | 508.14 | +32.19 | +6.76 % |

### C. Puente precio-volumen-mezcla (el resultado central del laboratorio)

| Componente | Contribución (£) | Peso relativo sobre la suma de magnitudes |
|---|---:|---:|
| Productos nuevos en P1 (674 códigos) | **+2 046 903.92** | 40.8 % |
| Efecto volumen del catálogo común | **−1 568 093.05** | 31.3 % |
| Productos discontinuados (990 códigos) | **−704 357.16** | 14.1 % |
| Efecto mezcla del catálogo común | **+577 550.82** | 11.5 % |
| Efecto precio del catálogo común | **−115 918.44** | 2.3 % |
| **Variación neta de ingresos** | **+236 086.10** | — |

Catálogo común: 3 230 productos · Variación del catálogo común: −£ 1 106 460.66 · Reconciliación verificada con diferencia de £ 0.00.

### D. Cohortes y clientes

| Indicador | Valor |
|---|---:|
| Clientes identificados en todo el archivo | 5 852 |
| Cohortes mensuales construidas | 25 |
| Cohortes con al menos 6 meses cumplidos | 19 |
| Retención media al mes 6, cohortes del primer año (12 cohortes) | **19.24 %** |
| Retención media al mes 6, cohortes del segundo año (7 cohortes) | **15.66 %** |
| Retención al mes 6 de la cohorte dic-2009 (951 clientes) | 37.6 % |
| Ingreso P1 de clientes nuevos (1 585 clientes) | £ 1 448 212.66 → £ 913.70 por cliente |
| Ingreso P1 de clientes recurrentes (2 708 clientes) | £ 6 776 786.90 → £ 2 502.51 por cliente |

### E. Segmentación por mercado

| Mercado | P0 (£) | P1 (£) | Variación (£) | Variación (%) | Clientes |
|---|---:|---:|---:|---:|---:|
| EIRE (Irlanda) | 352 563.30 | 263 709.97 | **−88 853.33** | −25.20 % | 3 |
| Denmark | 49 211.35 | 18 060.44 | −31 150.91 | **−63.30 %** | 11 |
| Sweden | 49 490.31 | 36 590.83 | −12 899.48 | −26.06 % | 19 |
| Greece | 14 285.67 | 3 879.53 | −10 406.14 | −72.84 % | — |
| United Arab Emirates | 8 408.45 | 1 864.78 | −6 543.67 | −77.82 % | — |
| Channel Islands | 24 032.79 | 19 799.14 | −4 233.65 | −17.62 % | 13 |
| Australia | 29 696.20 | 138 103.81 | **+108 407.61** | +365.06 % | 15 |
| United Kingdom | 8 076 575.70 | 8 153 163.34 | +76 587.64 | +0.95 % | 5 313 |
| France | 126 597.29 | 177 954.08 | +51 356.79 | +40.57 % | 92 |
| Japan | 5 607.54 | 37 416.37 | +31 808.83 | +567.25 % | — |
| Norway | 6 120.72 | 29 708.94 | +23 588.22 | +385.38 % | — |
| Germany | 177 907.85 | 198 356.98 | +20 449.13 | +11.49 % | 106 |

---

## I. Elemento de la capacidad terminal de la semana

Explica la variación de un resultado empresarial mediante la descomposición de los factores que la componen. Distingue los niveles descriptivo, diagnóstico y causal del análisis, y evita atribuir causalidad a una asociación observada. Construye cohortes de clientes, calcula tasas de retención comparables entre grupos de igual antigüedad e identifica el driver dominante de una variación, formulando una recomendación empresarial sustentada en cifras verificables y en el reconocimiento explícito de sus limitaciones.

## II. Seguridad

- Abstenerse de manipular hardware, conexiones eléctricas o de red sin la supervisión correspondiente.
- No ingerir alimentos ni bebidas dentro del laboratorio.
- Mantener la estación de trabajo, el mobiliario y los equipos en condiciones de orden y limpieza.
- No descargar ni instalar software no autorizado.
- Ejecutar el código exclusivamente en el entorno Google Colab.
- No alterar ni fabricar valores de los datos; toda decisión metodológica debe quedar debidamente documentada.

## III. Fundamento teórico

- Provost, F. y Fawcett, T. (2013). *Data Science for Business*. Capítulos 2 y 3.
- Sharda, R., Delen, D. y Turban, E. (2024). *Business Intelligence, Analytics, Data Science, and AI*. Capítulo 3.
- Fader, P. S. y Hardie, B. G. S. (2009). Probability models for customer-base analysis. *Journal of Interactive Marketing*, 23(1), 61-69.
- Knaflic, C. N. (2015). *Storytelling with Data*. Capítulos 2 y 3.

## IV. Normas empleadas

No resulta aplicable una norma técnica específica. Se adoptan buenas prácticas de reproducibilidad y trazabilidad: verificación de la huella criptográfica SHA-256 del conjunto de datos antes de su uso y atribución de la fuente conforme exige la licencia Creative Commons Attribution 4.0.

## V. Recursos

Computadora con acceso a internet · Cuenta de Google (Colab) y de GitHub · Notebook del laboratorio · Conjunto Online Retail II del UCI Machine Learning Repository · Librerías Polars, DuckDB y Plotly.

## VI. Metodología para el desarrollo de la tarea

El laboratorio se desarrolla en los equipos del proyecto integrador. Cada estudiante ejecuta el notebook, completa el código solicitado y registra sus respuestas. Entregable: notebook ejecutado, depositado en el repositorio del equipo, dentro de la carpeta `semana04/`.

---

# **Actividad 1 — Revisión de conceptos**

**Criterio de corrección.** No se exige una redacción idéntica a la que aquí se propone. Se exige que la definición del estudiante permita responder la *pregunta de apoyo* que acompaña a cada concepto. Una definición que no permite responderla es una definición insuficiente, aunque esté bien escrita. Se penaliza la transcripción literal de fuentes y la definición circular (del tipo «el efecto volumen es el efecto del volumen»).

---

### **1. Analítica diagnóstica**

**Definición.** Es el nivel de análisis que toma una variación ya medida y la descompone en los factores medibles con los que se relaciona, de modo que se pueda señalar *dónde* y *en qué componente* se originó el movimiento. No inventa una explicación: reparte una cifra observada entre partes que suman exactamente esa cifra.

**Formalmente.** Si un resultado $R$ pasó de $R_0$ a $R_1$, la analítica diagnóstica busca una partición

$$\Delta R = R_1 - R_0 = \sum_{j=1}^{J} E_j$$

donde cada $E_j$ es un efecto atribuible a un factor identificado y la igualdad se cumple de manera **exacta**, no aproximada. Esa exigencia de reconciliación es lo que distingue un diagnóstico de una narrativa: si los efectos no suman la variación observada, existe un factor no modelado y el reparto no es defendible.

**Respuesta a la pregunta de apoyo — ¿qué la distingue de la descriptiva y qué sigue sin poder afirmar?** La descriptiva responde *qué* cambió, *cuánto*, *dónde* y *cuándo*; la diagnóstica responde *con qué factores medibles se relaciona ese cambio*. Lo que la diagnóstica **sigue sin poder afirmar** es que esos factores *hayan producido* el cambio. Una descomposición es una identidad contable, no una relación causal: demuestra que la variación se reparte de cierta manera, no que si se hubiera intervenido sobre uno de los componentes el resultado habría sido distinto. Para afirmar eso se requiere un diseño experimental (asignación aleatoria) o cuasi-experimental (diferencias en diferencias, variables instrumentales, discontinuidad en la regresión), que este conjunto de datos no provee.

---

### 2. Driver de un resultado

**Definición.** Es un factor que, además de moverse junto con el resultado, forma parte de la aritmética que lo produce: al cambiar el driver, el resultado cambia por construcción, no por coincidencia. En un árbol de drivers cada nivel es una descomposición multiplicativa o aditiva del nivel superior, de manera que el resultado queda expresado como una función explícita de sus componentes.

**Formalmente.** Si el ingreso se escribe como

$$R = N_{\text{clientes}} \times f_{\text{frecuencia}} \times \bar{t}_{\text{ticket}}$$

entonces $N$, $f$ y $\bar{t}$ son drivers de $R$, porque la identidad se cumple por definición. En cambio, «la temperatura del mes» puede correlacionar con $R$ sin ser driver: no aparece en la identidad y su relación con $R$ podría desaparecer al controlar por otra variable.

**Respuesta a la pregunta de apoyo — ¿cómo se comprueba que una variable es driver y no una simple correlación?** Mediante tres comprobaciones sucesivas: (i) **aritmética**, verificando que la variable aparece en la identidad que define el resultado y que la descomposición reconcilia exactamente; (ii) **de estabilidad**, comprobando que la relación se sostiene al segmentar la población en subgrupos (si desaparece dentro de cada segmento, la asociación agregada era un artefacto de composición, fenómeno conocido como paradoja de Simpson); (iii) **de intervención**, que es la única concluyente y exige mover deliberadamente la variable y observar el resultado. Sin la tercera, lo correcto es hablar de *driver contable* y no de *causa*.

---

### 3. Efecto volumen

**Definición.** Es la parte de la variación del ingreso que se explica únicamente porque se vendieron más o menos unidades en total, manteniendo congelados tanto la composición del catálogo como los precios del periodo base.

**Formalmente.**

$$E_{\text{volumen}} = (Q_1 - Q_0)\cdot \bar{p}_0, \qquad \bar{p}_0 = \sum_{i} s_{0i}\, p_{0i}, \qquad s_{0i} = \frac{q_{0i}}{Q_0}$$

donde $Q_t=\sum_i q_{ti}$ es el volumen total del periodo $t$, $s_{0i}$ la participación del producto $i$ en el volumen del periodo base y $p_{0i}$ su precio efectivo en ese periodo. El término $\bar{p}_0$ es el **precio medio ponderado del periodo base**: el importe que, en promedio, aportaba cada unidad vendida antes de que cambiara nada.

La lectura es directa: el efecto volumen valoriza el cambio de unidades a los precios y a la mezcla de antes. Responde a la pregunta «si lo único que hubiera cambiado fuese la cantidad total vendida, ¿cuánto habría variado el ingreso?».

**Respuesta a la pregunta de apoyo — si el precio no cambia y los ingresos caen, ¿qué indica el efecto volumen?** Indica que la caída proviene de haber vendido menos unidades, y su magnitud cuantifica exactamente cuánto dinero costó esa pérdida de unidades valorizada al precio medio anterior. Si además la mezcla no cambió, el efecto volumen absorbería toda la variación y la lectura sería inequívoca: el problema es de demanda o de disponibilidad, no de política comercial de precios.

---

### 4. Efecto mezcla

**Definición.** Es la parte de la variación del ingreso que se explica porque cambió la **composición** de lo vendido —qué peso tiene cada producto dentro del total de unidades—, manteniendo congelados el volumen total del periodo final y los precios del periodo base. Es el efecto más sutil de los tres y el que con más frecuencia se confunde con el efecto precio.

**Formalmente.**

$$E_{\text{mezcla}} = Q_1 \cdot \sum_i (s_{1i} - s_{0i})\, p_{0i} \;=\; Q_1\left(\bar{p}_0^{\,s_1} - \bar{p}_0\right), \qquad \bar{p}_0^{\,s_1} = \sum_i s_{1i}\, p_{0i}$$

El término $\bar{p}_0^{\,s_1}$ es un **precio medio contrafactual**: el precio medio que se habría observado si se hubiera vendido con la composición del periodo final pero a los precios del periodo base. La diferencia $\bar{p}_0^{\,s_1} - \bar{p}_0$ aísla, en libras por unidad, cuánto se encareció o abarató el «carrito promedio» por el solo hecho de que la demanda se desplazó hacia otros productos.

**Respuesta a la pregunta de apoyo — ¿puede aumentar el ingreso sin vender más unidades ni subir precios?** Sí, y ese es precisamente el efecto mezcla. Si la empresa vende el mismo número total de unidades, con la misma lista de precios, pero una proporción mayor de esas unidades corresponde a productos caros, el ingreso sube sin que haya habido ni más volumen ni un aumento de precios. El caso simétrico —desplazamiento hacia productos baratos— produce una caída de ingreso que el gerente puede leer erróneamente como «bajamos los precios», cuando ningún precio se movió.

---

### 5. Efecto precio

**Definición.** Es la parte de la variación del ingreso que se explica porque cada producto se vendió a un precio efectivo distinto, manteniendo congeladas tanto la cantidad total como la composición del periodo final.

**Formalmente.**

$$E_{\text{precio}} = Q_1 \cdot \sum_i s_{1i}\,(p_{1i} - p_{0i}) \;=\; Q_1\left(\bar{p}_1 - \bar{p}_0^{\,s_1}\right), \qquad p_{ti} = \frac{r_{ti}}{q_{ti}}$$

Obsérvese que $p_{ti}$ **no es el precio de lista** sino el **precio efectivo**: el ingreso del producto dividido entre sus unidades. Esa definición es deliberada, porque absorbe descuentos, promociones, precios diferenciados por cliente y escalas por volumen, es decir, el precio al que la empresa realmente cobró y no al que decía cobrar.

**Respuesta a la pregunta de apoyo — ¿por qué debe calcularse sobre un catálogo común a ambos periodos?** Porque un producto que solo existe en uno de los dos periodos **no tiene precio de comparación**: no hay $p_{0i}$ contra el cual medir su $p_{1i}$, de modo que la diferencia $p_{1i}-p_{0i}$ es indefinida. Incluirlo obligaría a imputar un precio inventado, lo que introduciría en la cifra de precio un movimiento que en realidad es de catálogo. Por eso la descomposición se aplica sobre la intersección de ambos catálogos y las altas y bajas se cuantifican por separado, como dos componentes adicionales del puente.

---

### 6. Cohorte de clientes

**Definición.** Es el conjunto de clientes que comparten el mes de su **primera compra**, seguido a lo largo del tiempo. La pertenencia a la cohorte es permanente: un cliente que compró por primera vez en marzo de 2010 pertenece a la cohorte de marzo de 2010 para siempre, aunque siga comprando dos años después.

**Formalmente.** Para cada cliente $u$ se define su mes de origen

$$c(u) = \min_{v \in \text{compras}(u)} \text{mes}(v)$$

y su **antigüedad** en cualquier mes $m$ posterior

$$k = 12\,\big(\text{año}(m) - \text{año}(c(u))\big) + \big(\text{mes}(m) - \text{mes}(c(u))\big)$$

de modo que $k=0$ es el mes de la primera compra, $k=1$ el mes siguiente, y así sucesivamente.

**Respuesta a la pregunta de apoyo — ¿por qué la antigüedad se mide desde el mes de la primera compra y no desde enero?** Porque el comportamiento de un cliente depende mucho más del tiempo transcurrido desde que se incorporó que de la fecha del calendario. La caída de actividad más fuerte ocurre en los primeros meses de vida del cliente; si se midiera todo desde enero, un cliente captado en noviembre aparecería con «dos meses de historia» junto a otro captado en enero con doce, y la comparación mezclaría dos cosas distintas: la maduración natural del cliente y el momento del año. Realinear todas las cohortes en $k=0$ las pone en el mismo punto de partida y convierte la comparación en legítima.

---

### 7. Tasa de retención

**Definición.** Es la proporción de los clientes que estrenaron una cohorte que seguía comprando en un mes determinado de antigüedad.

**Formalmente.** Si $A_{c,k}$ es el conjunto de clientes de la cohorte $c$ con al menos una compra en el mes de antigüedad $k$,

$$\text{Ret}_c(k) = \frac{\left|A_{c,k}\right|}{\left|A_{c,0}\right|}\times 100$$

El denominador es siempre el **tamaño inicial de la cohorte**, nunca el del mes anterior. Por construcción $\text{Ret}_c(0)=100\,\%$ para toda cohorte, de modo que lo informativo no es el punto de partida sino la **pendiente** de la curva. Adviértase también que esta definición admite el «regreso»: un cliente que no compró en $k=3$ pero sí en $k=4$ cuenta como activo en $k=4$, razón por la cual la serie no es necesariamente decreciente. En este laboratorio ese fenómeno se observa con claridad: la cohorte de diciembre de 2009 cae a 35.0 % en el mes 1, retrocede a 33.3 % en el mes 2 y **sube** a 42.5 % en el mes 3, porque una parte de los mayoristas compra de manera intermitente y no mensual.

**Respuesta a la pregunta de apoyo — ¿qué significa una celda vacía en la matriz de retención de una cohorte reciente?** Significa **ausencia de información, no abandono**. Una cohorte nacida en octubre de 2011, dentro de un archivo que termina el 9 de diciembre de 2011, sencillamente todavía no ha vivido su mes 6: la celda está vacía porque ese mes aún no ocurrió. Leerla como retención cero es el error clásico del análisis de cohortes, y produce siempre la misma conclusión falsa —«las cohortes recientes se deterioran»— que no es un hallazgo sino un artefacto del truncamiento del periodo de observación.

---

### 8. Segmentación explicativa

**Definición.** Es la partición de una variación agregada en subgrupos —país, canal, tipo de cliente, categoría— con el propósito de localizar dónde se concentra el movimiento, priorizando por la **contribución absoluta** de cada segmento a la variación total y no por su variación porcentual.

**Formalmente.** Si $\Delta R = \sum_{g} \Delta R_g$ con $g$ recorriendo los segmentos, la prioridad se establece por $|\Delta R_g|$ (libras que el segmento aporta al movimiento) y no por $\Delta R_g / R_{0g}$ (intensidad del deterioro dentro del segmento). Ambas medidas responden preguntas distintas y son complementarias: la primera dice *cuánto dinero está en juego*, la segunda dice *qué tan enfermo está ese mercado*.

**Respuesta a la pregunta de apoyo — ¿por qué el segmento de mayor caída porcentual puede no ser el prioritario?** Porque el porcentaje se calcula sobre la base del propio segmento, y una base pequeña produce porcentajes espectaculares con importes triviales. En este laboratorio, los Emiratos Árabes Unidos caen **−77.82 %**, la mayor caída relativa de todo el conjunto, y sin embargo esa caída equivale a **£ 6 543.67**: apenas un 0.07 % de los ingresos del periodo base. EIRE cae solo **−25.20 %**, pero esa caída vale **£ 88 853.33**, trece veces más dinero. Priorizar por porcentaje llevaría a asignar el equipo comercial al mercado equivocado. La lectura correcta usa las dos dimensiones a la vez, que es precisamente lo que construye el gráfico de dispersión del Ejercicio 5.

---

# **Marco formal completo del puente precio-volumen-mezcla**

*(Material de apoyo para la explicación en pizarra, bloque de 8:05 a 8:25.)*

## Punto de partida: la identidad del ingreso

El ingreso de un periodo $t$ es la suma, sobre todos los productos, de unidades por precio:

$$R_t = \sum_{i} q_{ti}\, p_{ti}$$

Introduciendo el volumen total $Q_t = \sum_i q_{ti}$ y las participaciones $s_{ti} = q_{ti}/Q_t$ (que suman 1 por construcción), la identidad se reescribe como

$$R_t = Q_t \sum_i s_{ti}\,p_{ti} = Q_t \cdot \bar{p}_t$$

Esta reescritura es el corazón del método: **el ingreso es volumen total multiplicado por precio medio ponderado**, y el precio medio ponderado depende a la vez de los precios individuales y de la composición de la venta. Ahí está el origen de la confusión gerencial que el laboratorio busca disolver: cuando sube $\bar{p}$, el gerente concluye «subimos los precios», cuando en realidad $\bar{p}$ pudo subir sin que ningún $p_i$ se moviera, solo porque cambiaron los $s_i$.

## La descomposición encadenada

La variación total es $\Delta R = Q_1\bar{p}_1 - Q_0\bar{p}_0$. Para repartirla se introduce un **precio medio contrafactual** $\bar{p}_0^{\,s_1} = \sum_i s_{1i}p_{0i}$ —la mezcla nueva valorizada a los precios viejos— y se construyen tres pasos sucesivos, cada uno de los cuales cambia una sola cosa:

| Paso | Qué se mueve | Qué se mantiene fijo | Efecto |
|---|---|---|---|
| 1 | El volumen total, de $Q_0$ a $Q_1$ | Mezcla $s_0$ y precios $p_0$ | $E_{\text{vol}} = (Q_1-Q_0)\,\bar{p}_0$ |
| 2 | La mezcla, de $s_0$ a $s_1$ | Volumen $Q_1$ y precios $p_0$ | $E_{\text{mez}} = Q_1\left(\bar{p}_0^{\,s_1}-\bar{p}_0\right)$ |
| 3 | Los precios, de $p_0$ a $p_1$ | Volumen $Q_1$ y mezcla $s_1$ | $E_{\text{pre}} = Q_1\left(\bar{p}_1-\bar{p}_0^{\,s_1}\right)$ |

## Demostración de que la suma reconcilia exactamente

$$E_{\text{vol}}+E_{\text{mez}}+E_{\text{pre}} = (Q_1-Q_0)\bar{p}_0 + Q_1\bar{p}_0^{\,s_1} - Q_1\bar{p}_0 + Q_1\bar{p}_1 - Q_1\bar{p}_0^{\,s_1}$$

$$= Q_1\bar{p}_0 - Q_0\bar{p}_0 - Q_1\bar{p}_0 + Q_1\bar{p}_1 = Q_1\bar{p}_1 - Q_0\bar{p}_0 = R_1 - R_0 = \Delta R \qquad \blacksquare$$

Los términos $Q_1\bar{p}_0^{\,s_1}$ y $Q_1\bar{p}_0$ se cancelan por pares. **No queda residuo ni término cruzado**, y por eso el `assert` del notebook exige una diferencia menor a un céntimo: cualquier discrepancia superior no es un error de redondeo sino un error de construcción del código.

> **Advertencia metodológica que debe explicitarse ante la clase.** El orden de los pasos no es neutro. Existen otras descomposiciones válidas —la simétrica de Bennet, la de Fisher, la de Törnqvist— que reparten de manera distinta los términos de interacción entre volumen, mezcla y precio. Ninguna es «la verdadera»: todas reconcilian, pero atribuyen cantidades diferentes a cada efecto. Lo que un análisis serio exige no es elegir la correcta, sino **declarar cuál se usó**, porque dos analistas con métodos distintos obtendrán cifras distintas sin que ninguno se haya equivocado. Es exactamente la misma exigencia que se aplica a las reglas de calidad del dato.

## El puente completo cuando el catálogo cambia

La descomposición anterior requiere que un producto exista en ambos periodos. En datos reales eso no ocurre: aquí hay 990 productos **discontinuados** (estaban en P0 y desaparecieron) y 674 productos **nuevos** (aparecieron en P1). Como no tienen precio de comparación, se los cuantifica como bloques enteros y el puente se cierra así:

$$\Delta R_{\text{total}} = \underbrace{E_{\text{vol}}+E_{\text{mez}}+E_{\text{pre}}}_{\text{catálogo común: 3230 productos}} + \underbrace{R_1^{\text{nuevos}}}_{\text{altas}} - \underbrace{R_0^{\text{discontinuados}}}_{\text{bajas}}$$

Ocultar cualquiera de los dos bloques rompe la reconciliación y, lo que es peor, esconde el hallazgo: en este caso las altas y bajas de catálogo **son** la historia principal.

## Verificación numérica del caso, paso a paso

| Magnitud | Valor calculado |
|---|---:|
| $Q_0$ — unidades del catálogo común en P0 | 5 129 757 |
| $Q_1$ — unidades del catálogo común en P1 | 4 204 346 |
| $Q_1 - Q_0$ | **−925 411** (−18.04 %) |
| $\bar{p}_0$ — precio medio ponderado en P0 | £ 1.694483 |
| $\bar{p}_0^{\,s_1}$ — mezcla nueva a precios viejos | £ 1.831853 |
| $\bar{p}_1$ — precio medio ponderado en P1 | £ 1.804282 |
| $E_{\text{vol}} = (-925\,411)\times 1.694483$ | **−£ 1 568 093.05** |
| $E_{\text{mez}} = 4\,204\,346\times(1.831853-1.694483)$ | **+£ 577 550.82** |
| $E_{\text{pre}} = 4\,204\,346\times(1.804282-1.831853)$ | **−£ 115 918.44** |
| Suma de los tres efectos | −£ 1 106 460.66 |
| Variación real del catálogo común | −£ 1 106 460.66 |
| **Diferencia** | **£ 0.00** ✔ |

**Lectura de esta tabla en lenguaje de negocio.** Cada unidad vendida del catálogo común pasó de aportar £ 1.6945 a aportar £ 1.8043, un aumento de £ 0.1098 por unidad. Ese aumento **no vino de los precios**: la mezcla, por sí sola, habría llevado el aporte hasta £ 1.8319 (+£ 0.1374 por unidad), y los precios efectivos lo retrocedieron en £ 0.0276. Es decir, **la empresa cobró en promedio un poco menos por producto y, aun así, su carrito promedio se encareció, porque vendió cosas distintas.** Quien lea únicamente el ticket promedio (£ 475.95 → £ 508.14, +6.76 %) concluirá lo contrario, y esa es la equivocación que el puente evita.

---

# BLOQUE 0 — Activación conceptual

| Nivel | Pregunta que responde | Lo que NO permite afirmar |
|---|---|---|
| Descriptivo | ¿Qué cambió, cuánto, dónde y cuándo? | Por qué cambió. |
| Diagnóstico | ¿Con qué factores medibles se relaciona el cambio? | Que esos factores lo hayan producido. |
| Causal | ¿Qué intervención produjo el efecto? | Nada adicional, pero exige un diseño experimental o cuasi-experimental. |

## ✅ Pregunta 1 — Clasificación previa · RESUELTA

**a) «Los ingresos del segundo año fueron superiores en 2.5 %.» → DESCRIPTIVA.**

Es una medición de un hecho ocurrido: compara dos magnitudes del mismo indicador en dos periodos y reporta la diferencia. No introduce ningún factor explicativo ni afirma nada sobre el mecanismo. Es verificable —la cifra exacta es **+£ 236 086.10, equivalente a +2.51 %**— y es también, como se verá en la Pregunta 5, profundamente engañosa si se la deja sola. Una afirmación descriptiva puede ser simultáneamente cierta e inútil para decidir.

**b) «La caída de unidades se concentra en los productos que dejaron de ofrecerse.» → DIAGNÓSTICA.**

Aquí ya no se describe: se **localiza** la variación dentro de una partición del dato. La afirmación relaciona un resultado (la caída de 377 923 unidades, −6.72 %) con un factor medible (el subconjunto de 990 productos discontinuados, que en P0 movían £ 704 357.16 y 496 903 unidades). Es diagnóstica porque señala *dónde* está el movimiento y permite cuantificar cuánto pesa ese componente, pero **no afirma que la desaparición de esos productos haya causado la caída**: podría ser al revés —dejaron de ofrecerse *porque* ya no se vendían— y el dato, por sí solo, no distingue una dirección de la otra.

**c) «Retirar esos productos del catálogo provocó la caída de unidades.» → CAUSAL.**

El verbo «provocó» introduce una afirmación contrafactual: sostiene que, de no haberse retirado los productos, las unidades no habrían caído. Con este conjunto de datos **no puede sostenerse**, por tres razones concretas: (i) existe **causalidad inversa** plausible, ya que un minorista suele descontinuar justamente lo que se vende poco; (ii) existen **factores de confusión** no observados —el conjunto no contiene stock, campañas, precios de la competencia ni decisiones de compra—; y (iii) **no existe grupo de control**: no hay un conjunto comparable de productos mantenidos en catálogo bajo condiciones equivalentes. Sostener (c) exigiría un experimento —retirar productos aleatoriamente en unos mercados y no en otros— o un cuasi-experimento con un contrafactual creíble.

> **Regla de aula que conviene fijar aquí.** El salto indebido no está en la cifra, sino en el verbo. «Se concentra en», «se asocia con», «coincide con» son diagnósticos. «Provocó», «causó», «se debe a», «por culpa de» son causales, y exigen un diseño que este dato no tiene.

In [1]:
# Verificamos el entorno de Python
import sys, platform

## Obtenemos la versión de Python utilizada
print("Python  :", sys.version.split()[0])

## Identificamos el sistema operativo
print("Sistema :", platform.system())

Python  : 3.13.15
Sistema : Linux


In [2]:
# Instalamos las librerías necesarias para el laboratorio
# Fijamos versiones para mantener la reproducibilidad del notebook
!pip install -q polars==1.17.1 duckdb==1.1.3

# Importamos las librerías que utilizaremos en el análisis
import polars as pl
import duckdb
import plotly.graph_objects as go
import plotly.express as px

# Configuramos la cantidad máxima de filas que Polars mostrará en las tablas
pl.Config.set_tbl_rows(20)

## Configuramos el ancho máximo de las tablas para facilitar su lectura
pl.Config.set_tbl_width_chars(160)

## Mostramos los números completos, evitando la notación científica
pl.Config.set_fmt_float("full")

# Verificamos las versiones instaladas
print("polars :", pl.__version__)
print("duckdb :", duckdb.__version__)

# Confirmamos que el entorno está listo para comenzar el laboratorio
print("\nEntorno listo.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 40.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.2/20.2 MB 21.1 MB/s eta 0:00:00
polars : 1.17.1
duckdb : 1.1.3

Entorno listo.


# BLOQUE 1 — Descarga, trazabilidad y control de calidad

Un análisis solo vale lo que vale su fuente. Este bloque descarga el conjunto de datos, comprueba que sea exactamente el publicado y levanta un inventario de sus problemas de calidad. **Obsérvese el orden: primero se mide cuánto hay de cada problema y recién después se decide qué hacer con él.** Descartar filas antes de saber cuántas son ni cuánto dinero mueven es una forma silenciosa de alterar el resultado.

> **Nota para el docente.** La huella SHA-256 no es un adorno de seguridad informática. Cumple la misma función que el sello notarial en un contrato: acredita que el archivo analizado es idéntico al publicado, bit por bit. Si un solo valor cambiara —una celda editada a mano, una fila borrada por accidente— la huella sería completamente distinta. Es la manera de que un tercero pueda reproducir el análisis y llegar a la misma cifra.

In [3]:
# Descargamos el conjunto de datos y verificamos que sea exactamente el publicado
# La huella SHA-256 permite comprobar que el archivo no fue alterado

import hashlib, pathlib, urllib.request

# Definimos la URL oficial del conjunto de datos
URL = ("https://raw.githubusercontent.com/Rociosayan/"
       "analitica-empresarial-integrada/main/semana04/datos/"
       "online_retail_II.parquet")

## Guardamos la huella SHA-256 publicada para comparar el archivo descargado
HUELLA_PUBLICADA = "8f64c20d17d38ab02c0dfddda323574e0ee8c34e719df6ea574d16a6e3678e96"

# Definimos el nombre y ubicación del archivo
ARCHIVO = pathlib.Path("online_retail_II.parquet")

# Descargamos el archivo solo si todavía no existe
if not ARCHIVO.exists():
    urllib.request.urlretrieve(URL, ARCHIVO)

# Calculamos la huella SHA-256 del archivo descargado
huella = hashlib.sha256(ARCHIVO.read_bytes()).hexdigest()

# Mostramos el tamaño y la huella para comprobar la trazabilidad
print("Tamaño        :", f"{ARCHIVO.stat().st_size:,} bytes")
print("SHA-256       :", huella)

## Comparamos la huella calculada con la huella publicada
print("¿Coincide?    :",
      "sí" if huella == HUELLA_PUBLICADA else "NO — avise a la docente")

Tamaño        : 7,283,898 bytes
SHA-256       : 8f64c20d17d38ab02c0dfddda323574e0ee8c34e719df6ea574d16a6e3678e96
¿Coincide?    : sí


### **Verificación del archivo**

- El archivo tiene un tamaño de **7,283,898 bytes**.
- La huella **SHA-256 coincide** con la publicada.
- Esto confirma que el archivo corresponde al dataset oficial y **no fue alterado**.
- Podemos continuar con el análisis de calidad de los datos.

In [4]:
# Creamos una ficha de trazabilidad para documentar el origen de los datos
# y las principales características del conjunto utilizado en el análisis.

FICHA = {
    "Conjunto":  "Online Retail II",
    "Origen":    "UCI Machine Learning Repository, conjunto n.° 502",
    "Enlace":    "https://archive.ics.uci.edu/dataset/502/online+retail+ii",
    "Donante":   "Dr. Daqing Chen, London South Bank University",
    "Licencia":  "Creative Commons Attribution 4.0 (CC BY 4.0)",
    "Cobertura": "01/12/2009 a 09/12/2011",
    "Moneda":    "Libra esterlina (GBP)",
}

# Recorremos cada campo de la ficha y mostramos su información
for campo, valor in FICHA.items():
    print(f"{campo:<10}: {valor}")## <10 reserva 10 espacios para alinear los nombres de los campos

Conjunto  : Online Retail II
Origen    : UCI Machine Learning Repository, conjunto n.° 502
Enlace    : https://archive.ics.uci.edu/dataset/502/online+retail+ii
Donante   : Dr. Daqing Chen, London South Bank University
Licencia  : Creative Commons Attribution 4.0 (CC BY 4.0)
Cobertura : 01/12/2009 a 09/12/2011
Moneda    : Libra esterlina (GBP)


### **Origen y características de los datos**

- El conjunto utilizado es **Online Retail II**.
- Proviene del **UCI Machine Learning Repository, conjunto n.° 502**.
- El donante es **Dr. Daqing Chen, London South Bank University**.
- La licencia es **Creative Commons Attribution 4.0 (CC BY 4.0)**.
- La cobertura comprende del **01/12/2009 al 09/12/2011**.
- La moneda utilizada es la **libra esterlina (GBP)**.
- La ficha permite dejar registrada la **procedencia y las características principales** de los datos utilizados.

In [5]:
# Cargamos el conjunto de datos y renombramos las columnas al castellano.
# Esto facilita su uso en las consultas y análisis posteriores.

crudo = pl.read_parquet(ARCHIVO).rename({
    "Invoice":     "factura",
    "StockCode":   "codigo",
    "Description": "descripcion",
    "Quantity":    "cantidad",
    "InvoiceDate": "fecha",
    "Price":       "precio",
    "Customer ID": "cliente_id",
    "Country":     "pais",
})

# Mostramos la cantidad de filas y columnas del conjunto de datos
print("Filas    :", f"{crudo.height:,}")
print("Columnas :", crudo.width)

## Verificamos el periodo cubierto por los datos
print("Periodo  :", crudo["fecha"].min(), "a", crudo["fecha"].max())

# Mostramos las primeras 5 filas para revisar la estructura de los datos
print()
print(crudo.head(5))

Filas    : 1,067,371
Columnas : 8
Periodo  : 2009-12-01 07:45:00 a 2011-12-09 12:50:00

shape: (5, 8)
┌─────────┬────────┬─────────────────────────────────┬──────────┬─────────────────────┬────────┬────────────┬────────────────┐
│ factura ┆ codigo ┆ descripcion                     ┆ cantidad ┆ fecha               ┆ precio ┆ cliente_id ┆ pais           │
│ ---     ┆ ---    ┆ ---                             ┆ ---      ┆ ---                 ┆ ---    ┆ ---        ┆ ---            │
│ str     ┆ str    ┆ str                             ┆ i64      ┆ datetime[ns]        ┆ f64    ┆ f64        ┆ str            │
╞═════════╪════════╪═════════════════════════════════╪══════════╪═════════════════════╪════════╪════════════╪════════════════╡
│ 489434  ┆ 85048  ┆ 15CM CHRISTMAS GLASS BALL 20 L… ┆ 12       ┆ 2009-12-01 07:45:00 ┆ 6.95   ┆ 13085      ┆ United Kingdom │
│ 489434  ┆ 79323P ┆ PINK CHERRY LIGHTS              ┆ 12       ┆ 2009-12-01 07:45:00 ┆ 6.75   ┆ 13085      ┆ United Kingdom │
│ 489434 

### **Carga y estructura del conjunto de datos**

- Se cargaron **1,067,371 filas** y **8 columnas**.
- Los datos abarcan desde el **01/12/2009 07:45:00** hasta el **09/12/2011 12:50:00**.
- Las columnas fueron renombradas al castellano: **factura, código, descripción, cantidad, fecha, precio, cliente_id y país**.
- Las primeras 5 filas confirman que los datos se cargaron correctamente y contienen información de **facturas, productos, cantidades, precios, clientes y países**.
- La columna **cliente_id** aparece como numérica (`f64`) y puede contener valores faltantes, aspecto que será importante revisar durante el control de calidad.

In [6]:
# Inventario de problemas de calidad
## Primero medimos los problemas antes de corregir o eliminar datos

SERVICIOS = (r"(?i)^(POST|DOT|M|C2|C3|D|S|B|BANK CHARGES|ADJUST\d?"
             r"|AMAZONFEE|PADS|CRUK|TEST\d+|GIFT|gift_.*)$")

diagnostico = {
    "Filas totales":
        crudo.height,  ## Cantidad total de registros del dataset

    "Filas duplicadas exactas":
        crudo.height - crudo.unique().height,  ## Registros repetidos exactamente

    "Cancelaciones (factura que empieza con C)":
        crudo.filter(pl.col("factura").str.starts_with("C")).height,  ## Facturas marcadas como cancelaciones

    "Cantidad menor o igual a cero":
        crudo.filter(pl.col("cantidad") <= 0).height,  ## Detecta cantidades no válidas para una venta

    "Precio menor o igual a cero":
        crudo.filter(pl.col("precio") <= 0).height,  ## Detecta precios no válidos para una venta

    "Cliente sin identificar":
        crudo.filter(pl.col("cliente_id").is_null()).height,  ## Registros sin cliente identificado

    "Servicios y ajustes, no productos":
        crudo.filter(pl.col("codigo").str.contains(SERVICIOS)).height,  ## Identifica servicios y ajustes que no son productos
}

# Mostramos la cantidad y porcentaje de cada problema
for problema, cantidad in diagnostico.items():
    print(f"{problema:<44} {cantidad:>9,}   "  ## Alinea los resultados para facilitar su lectura
          f"({100 * cantidad / crudo.height:5.2f} %)")  ## Calcula el porcentaje sobre el total

Filas totales                                1,067,371   (100.00 %)
Filas duplicadas exactas                        34,335   ( 3.22 %)
Cancelaciones (factura que empieza con C)       19,494   ( 1.83 %)
Cantidad menor o igual a cero                   22,950   ( 2.15 %)
Precio menor o igual a cero                      6,207   ( 0.58 %)
Cliente sin identificar                        243,007   (22.77 %)
Servicios y ajustes, no productos                5,932   ( 0.56 %)


### **Inventario de calidad de los datos**

- Se analizaron **1,067,371 filas** en total.
- Se encontraron **34,335 filas duplicadas**, equivalentes al **3.22 %**.
- Se identificaron **19,494 cancelaciones**, equivalentes al **1.83 %**.
- Hay **22,950 registros con cantidad menor o igual a cero**, que representan el **2.15 %**.
- Se encontraron **6,207 registros con precio menor o igual a cero**, equivalentes al **0.58 %**.
- **243,007 registros no tienen cliente identificado**, siendo el problema más grande con **22.77 %** del total.
- Se identificaron **5,932 registros de servicios y ajustes**, equivalentes al **0.56 %**.
- Estos resultados permiten conocer la **magnitud de cada problema antes de aplicar las reglas de limpieza**.

In [7]:
# Revisamos los códigos que no corresponden a productos antes de descartarlos
## Así verificamos qué representan y si tienen una presencia importante en los datos

(crudo
 .filter(pl.col("codigo").str.contains(SERVICIOS))  ## Filtramos servicios y ajustes
 .group_by("codigo")  ## Agrupamos los registros según el código
 .agg(pl.len().alias("lineas"),  ## Contamos cuántas líneas tiene cada código
      pl.col("descripcion").first().alias("descripcion"))  ## Mostramos su descripción
 .sort("lineas", descending=True)  ## Ordenamos de mayor a menor cantidad de líneas
 .head(10))  ## Mostramos los 10 códigos con más registros

codigo,lineas,descripcion
str,u32,str
"""POST""",2122,"""POSTAGE"""
"""DOT""",1446,"""DOTCOM POSTAGE"""
"""M""",1421,"""Manual"""
"""C2""",282,"""CARRIAGE"""
"""D""",177,"""Discount"""
"""S""",104,"""SAMPLES"""
"""BANK CHARGES""",102,""" Bank Charges"""
"""ADJUST""",67,"""Adjustment by john on 26/01/20…"
"""AMAZONFEE""",43,"""AMAZON FEE"""


### **Códigos de servicios y ajustes**

- El código con mayor cantidad de registros es **POST (POSTAGE)** con **2,122 líneas**.
- Le siguen **DOT (DOTCOM POSTAGE)** con **1,446 líneas** y **M (Manual)** con **1,421 líneas**.
- También aparecen **C2 (CARRIAGE)** con **282**, **D (Discount)** con **177** y **S (SAMPLES)** con **104 líneas**.
- Se identificaron además **BANK CHARGES (102)**, **ADJUST (67)**, **AMAZONFEE (43)** y **gift_0001_20 (29)**.
- Estos códigos representan **servicios, descuentos, ajustes, cargos y otros conceptos**, por lo que no corresponden directamente a productos vendidos.
- Por ello, deben considerarse dentro de las reglas de limpieza antes de realizar el análisis de productos.

## ✅ Pregunta 2 — Decisiones de calidad ·
*De los problemas listados, el de mayor volumen es el de las líneas sin cliente identificado: 243 007 filas, un **22.77 %** del archivo.*

**a) ¿Por qué esas líneas sí pueden usarse para calcular ingresos?**

Porque el ingreso de una línea se calcula con dos campos que están completos: `cantidad × precio`. La ausencia del identificador del cliente no afecta en absoluto esa aritmética. La venta ocurrió, el dinero entró, el producto salió del almacén; lo único que falta es saber **a quién** se le vendió. En un comercio electrónico esas líneas corresponden típicamente a compras de invitado, a pedidos procesados por canales que no capturaban el identificador, o a ventas de mostrador registradas sin cuenta. Excluirlas del cálculo de ingresos equivaldría a sostener que una cuarta parte de las ventas de la empresa no existió, lo cual es falso y produciría un estado de resultados equivocado.

**b) ¿Por qué no pueden usarse para construir cohortes?**

Porque toda la maquinaria de cohortes descansa sobre la posibilidad de **seguir a la misma persona a lo largo del tiempo**. Para asignar a un cliente su mes de origen $c(u)=\min\,\text{mes}(v)$ hay que poder reconocerlo en compras sucesivas; sin identificador, cada línea es un individuo anónimo e irrepetible. Peor aún: si se les asignara un identificador ficticio, cada transacción pasaría a ser un «cliente nuevo que nunca volvió», y la retención calculada se desplomaría artificialmente. Por eso el notebook construye las cohortes solo sobre los **5 852 clientes identificados**, y esa restricción debe declararse en el informe: el análisis de retención describe al subconjunto identificado, no a toda la base de compradores.

**c) ¿Qué distorsión introduciría descartarlas desde el inicio?**

Tres distorsiones simultáneas, todas en el mismo sentido:

1. **Subestimación del nivel de ingresos.** Se perdería el importe facturado en esas 243 007 líneas, cifra nada menor tratándose de casi una de cada cuatro.
2. **Sesgo de composición entre mercados y periodos.** Las compras anónimas no se distribuyen de manera uniforme: dependen del canal de venta, y un canal puede pesar más en un periodo o en un país que en otro. Al eliminarlas, la comparación P0 contra P1 dejaría de ser homogénea y parte de la variación observada sería un artefacto del filtro, no un hecho del negocio.
3. **Pérdida de la trazabilidad de la decisión.** Descartar antes de medir impide saber cuánto se descartó. La regla profesional es la inversa y el notebook la respeta: **medir primero, decidir después y declarar siempre.**

> **Principio general que este bloque enseña.** No existe una tabla «limpia» única. Existen tablas construidas bajo reglas explícitas. El notebook aplica cuatro —quitar duplicados exactos, excluir cancelaciones, exigir cantidad y precio positivos, y separar servicios de productos— y con ellas descarta 64 031 filas, un **6.00 %** del total. Otro analista, con reglas distintas, obtendría cifras distintas sin haberse equivocado. Lo que no es admisible es no poder decir qué reglas se aplicaron.

# BLOQUE 2 — Transacciones válidas y comparación temporal

Con el inventario a la vista se construye la tabla de transacciones válidas aplicando cuatro reglas explícitas. Cada regla es, en rigor, **una definición de qué cuenta como venta**.

| Regla | Qué excluye | Justificación económica |
|---|---|---|
| `.unique()` | 34 335 filas duplicadas exactas | Una fila repetida es un artefacto del sistema, no una venta adicional. |
| Factura sin prefijo `C` | 19 494 líneas de cancelación | Una cancelación no es una venta; es su reverso. Incluirla con signo negativo mezclaría dos periodos, porque la devolución de una compra de P0 puede registrarse en P1. |
| `cantidad > 0` y `precio > 0` | Cantidades ≤ 0 y precios ≤ 0 | Sin unidades o sin precio no hay ingreso que medir. Los precios en cero corresponden a muestras, obsequios y ajustes de inventario. |
| Código fuera de `SERVICIOS` | 5 932 líneas de envío, ajustes y comisiones | Los portes (`POST`, `DOT`, `C2`), los ajustes manuales (`M`, `ADJUST`), las comisiones bancarias y las de Amazon no son producto vendido, y su precio unitario no es comparable con el de un producto. |

Después se delimitan los dos periodos. **Se toman doce meses exactos en cada caso, de diciembre a noviembre**, y la razón es decisiva: el conjunto termina el 9 de diciembre de 2011. Incluir ese mes compararía doce meses contra once meses y nueve días, y **fabricaría una caída que no ocurrió**. Quedan fuera 24 753 filas, que el notebook cuantifica y declara en lugar de silenciar.

In [8]:
# Construimos la tabla de transacciones válidas aplicando las reglas de calidad
## Cada filtro define qué registros se consideran ventas para el análisis

validas = (
    crudo
    .unique()  ## Eliminamos filas duplicadas exactas

    .filter(~pl.col("factura").str.starts_with("C"))  ## Excluimos las cancelaciones

    .filter((pl.col("cantidad") > 0) & (pl.col("precio") > 0))  ## Exigimos cantidad y precio positivos

    .filter(~pl.col("codigo").str.contains(SERVICIOS))  ## Excluimos servicios y ajustes

    .with_columns(
        (pl.col("cantidad") * pl.col("precio")).alias("ingreso"),  ## Calculamos el ingreso por línea
        pl.col("fecha").dt.date().alias("dia"),  ## Extraemos la fecha sin la hora
    )
)

# Comparamos las filas originales con las transacciones válidas
print(f"Filas de partida : {crudo.height:>9,}")  ## Total de filas originales
print(f"Filas válidas    : {validas.height:>9,}")  ## Filas que cumplen las reglas de venta

## Calculamos cuántas filas fueron descartadas y qué porcentaje representan
print(f"Descartadas      : {crudo.height - validas.height:>9,} "
      f"({100 * (crudo.height - validas.height) / crudo.height:.2f} %)")

Filas de partida : 1,067,371
Filas válidas    : 1,003,340
Descartadas      :    64,031 (6.00 %)


### **Transacciones válidas**

- Se partió de **1,067,371 filas** del conjunto original.
- Después de aplicar las reglas de limpieza, quedaron **1,003,340 transacciones válidas**.
- Se descartaron **64,031 filas**, equivalentes al **6.00 %** del total.
- Esto significa que el **94.00 % de los registros** quedó disponible para continuar con el análisis.
- Las transacciones válidas cumplen con las **reglas definidas para considerar una venta**.

In [9]:
# Definimos dos periodos de doce meses exactos para realizar una comparación justa
## Evitamos usar diciembre de 2011 porque sus datos solo llegan hasta el día 9

INICIO_P0, FIN_P0 = pl.date(2009, 12, 1), pl.date(2010, 11, 30)  ## Periodo base: dic-2009 a nov-2010
INICIO_P1, FIN_P1 = pl.date(2010, 12, 1), pl.date(2011, 11, 30)  ## Periodo comparado: dic-2010 a nov-2011

validas = validas.with_columns(
    pl.when((pl.col("dia") >= INICIO_P0) & (pl.col("dia") <= FIN_P0)).then(pl.lit("P0"))
      .when((pl.col("dia") >= INICIO_P1) & (pl.col("dia") <= FIN_P1)).then(pl.lit("P1"))
      .otherwise(None)
      .alias("periodo")
)

# Contamos las filas que no pertenecen a ninguno de los dos periodos
## Estas filas corresponden principalmente a diciembre de 2011, que está incompleto
fuera = validas.filter(pl.col("periodo").is_null()).height

print(f"P0: dic-2009 a nov-2010     P1: dic-2010 a nov-2011")
print(f"Filas fuera de ambos periodos (diciembre de 2011 incompleto): {fuera:,}")  ## Registros excluidos de la comparación

# Conservamos únicamente las filas pertenecientes a P0 o P1
comparables = validas.filter(pl.col("periodo").is_not_null())

## Obtenemos el total de filas que pueden compararse entre ambos periodos
print(f"Filas comparables: {comparables.height:,}")

P0: dic-2009 a nov-2010     P1: dic-2010 a nov-2011
Filas fuera de ambos periodos (diciembre de 2011 incompleto): 24,753
Filas comparables: 978,587


### **Periodos comparables**

- Se definieron dos periodos de **12 meses exactos**: P0 de **dic-2009 a nov-2010** y P1 de **dic-2010 a nov-2011**.
- Se identificaron **24,753 filas fuera de ambos periodos**, correspondientes al tramo incompleto de diciembre de 2011.
- Finalmente, quedaron **978,587 filas comparables** para realizar el análisis entre P0 y P1.
- De esta manera, la comparación se realiza sobre **periodos homogéneos**, evitando que el diciembre de 2011 incompleto distorsione los resultados.

In [10]:
# Realizamos la comparación temporal entre P0 y P1
## Este análisis es descriptivo: muestra qué cambió y cuánto, pero todavía no explica por qué

resumen = (
    comparables
    .group_by("periodo")  ## Agrupamos las transacciones según P0 y P1
    .agg(
        pl.col("ingreso").sum().alias("ingresos"),  ## Calculamos los ingresos totales
        pl.col("cantidad").sum().alias("unidades"),  ## Calculamos las unidades vendidas
        pl.col("factura").n_unique().alias("facturas"),  ## Contamos las facturas únicas
        pl.col("cliente_id").n_unique().alias("clientes"),  ## Contamos los clientes identificados
        pl.col("codigo").n_unique().alias("productos"),  ## Contamos los productos distintos
    )
    .sort("periodo")  ## Ordenamos los resultados de P0 a P1
)

# Separamos los resultados de los dos periodos para calcular sus variaciones
base, final = resumen.row(0, named=True), resumen.row(1, named=True)

print(f"{'Indicador':<12}{'P0':>16}{'P1':>16}{'Variación':>16}{'%':>10}")

for indicador in ["ingresos", "unidades", "facturas", "clientes", "productos"]:
    a, b = base[indicador], final[indicador]
    print(f"{indicador:<12}{a:>16,.0f}{b:>16,.0f}"
          f"{b - a:>16,.0f}{100 * (b - a) / a:>9.2f}%")  ## Calculamos la variación absoluta y porcentual

# Calculamos el ticket promedio dividiendo ingresos entre facturas
## Permite observar cuánto ingreso representa, en promedio, cada factura
ticket_p0 = base["ingresos"] / base["facturas"]
ticket_p1 = final["ingresos"] / final["facturas"]

print(f"\nTicket promedio  P0: £ {ticket_p0:,.2f}   P1: £ {ticket_p1:,.2f}")

Indicador                 P0              P1       Variación         %
ingresos           9,396,642       9,632,728         236,086     2.51%
unidades           5,626,660       5,248,737        -377,923    -6.72%
facturas              19,743          18,957            -786    -3.98%
clientes               4,240           4,294              54     1.27%
productos              4,220           3,904            -316    -7.49%

Ticket promedio  P0: £ 475.95   P1: £ 508.14


### **Comparación de resultados entre P0 y P1**

Los ingresos aumentaron de **£9,396,642 a £9,632,728**, representando un crecimiento de **£236,086 (+2.51 %)**. Sin embargo, las unidades vendidas disminuyeron en **377,923 (-6.72 %)** y las facturas en **786 (-3.98 %)**.

A pesar de esta reducción, el **ticket promedio aumentó de £475.95 a £508.14 (+6.76 %)**. Además, los clientes identificados crecieron ligeramente en **54 (+1.27 %)**, mientras que los productos distintos disminuyeron en **316 (-7.49 %)**.

El principal hallazgo descriptivo es que **los ingresos crecieron aunque se vendieron menos unidades y se emitieron menos facturas**. Esto indica que debemos realizar la **descomposición de los drivers** para determinar qué factor explica principalmente esta variación.

In [11]:
# Construimos la serie mensual de ingresos para observar su comportamiento en el tiempo
## El gráfico permite identificar si la variación anual es sostenida o se concentra en meses atípicos

mensual = (
    comparables
    .with_columns(
        pl.col("fecha").dt.truncate("1mo").dt.date().alias("mes")  ## Convertimos cada fecha al mes correspondiente
    )
    .group_by(["periodo", "mes"])  ## Agrupamos los ingresos por periodo y mes
    .agg(
        pl.col("ingreso").sum().alias("ingresos")  ## Sumamos los ingresos de cada mes
    )
    .sort("mes")  ## Ordenamos cronológicamente los meses
)

# Creamos el gráfico de líneas para comparar los ingresos mensuales de P0 y P1
figura = px.line(
    mensual.to_pandas(),
    x="mes",
    y="ingresos",
    color="periodo",
    markers=True,
    labels={
        "mes": "Mes",
        "ingresos": "Ingresos (£)",
        "periodo": "Periodo"
    }
)

# Configuramos la presentación del gráfico
figura.update_layout(
    title="Ingresos mensuales por periodo",
    height=420,
    hovermode="x unified"
)

# Mostramos el gráfico
figura.show()

### **Evolución mensual de los ingresos**

El gráfico muestra que los ingresos presentan **variaciones importantes mes a mes** en ambos periodos, por lo que el crecimiento anual no se explica por un aumento constante durante todos los meses.

En **P0**, los ingresos terminan con un fuerte incremento, alcanzando aproximadamente **£1.42 millones en noviembre de 2010**. En **P1**, también se observa un crecimiento hacia el final del periodo, llegando aproximadamente a **£1.45 millones en noviembre de 2011**.

Además, P1 presenta meses con ingresos cercanos a **£500 mil**, especialmente en febrero y abril de 2011, mientras que posteriormente los ingresos aumentan con fuerza desde agosto.

Por tanto, la variación anual de **+2.51 %** parece estar influenciada por **varios meses de comportamiento atípico o de fuerte crecimiento**, especialmente al final de cada periodo. Esto justifica continuar con la **descomposición de ingresos para identificar qué driver explica el cambio**.

## ✅ Pregunta 3 — La paradoja

*Los ingresos suben 2.51 % (+£ 236 086) mientras las unidades caen 6.72 % (−377 923). Las facturas caen 3.98 % y los clientes identificados suben apenas 1.27 %.*

**a) ¿Qué situación de negocio podría producir ese resultado?**

Varias situaciones son compatibles con esas cifras, y enumerarlas todas es parte del ejercicio diagnóstico. Las tres más plausibles en un mayorista de artículos de regalo son:

1. **Desplazamiento del catálogo hacia productos de mayor valor unitario.** Se venden menos piezas, pero cada pieza vale más. Es el efecto mezcla, y en este caso es real y positivo: **+£ 577 550.82**. El precio medio ponderado del catálogo común pasa de £ 1.6945 a £ 1.8043 por unidad sin que los precios individuales hayan subido.
2. **Renovación del catálogo.** Entran 674 referencias nuevas que aportan **£ 2 046 903.92**, un **21.25 % de los ingresos de P1**, con un precio medio de **£ 1.96 por unidad**; salen 990 referencias que aportaban **£ 704 357.16** a un precio medio de **£ 1.42**. El catálogo se renovó *hacia arriba* en valor unitario.
3. **Pérdida de volumen en el surtido histórico.** El catálogo común pierde 925 411 unidades (−18.04 %), una caída mucho más severa que el −6.72 % agregado, precisamente porque los productos nuevos compensan una parte importante de esa pérdida.

La combinación que efectivamente ocurrió es la tercera junto con las dos primeras: **la empresa perdió mucho volumen en lo que ya vendía y lo compensó con productos nuevos más caros.** Esa es una descripción del hecho, no todavía una explicación de por qué ocurrió.

**b) ¿El ticket promedio subió porque subieron los precios?**

**No puede sostenerse con la información disponible hasta este punto del notebook, y además resulta ser falso cuando se calcula el puente.** El ticket promedio pasó de £ 475.95 a £ 508.14 (+6.76 %), pero el ticket es un cociente entre dos magnitudes que se mueven a la vez:

$$\bar{t} = \frac{R}{F} = \frac{\text{ingresos}}{\text{número de facturas}}$$

Ese cociente puede subir por al menos cuatro razones distintas, y el dato agregado no permite distinguirlas: (i) porque subieron los precios; (ii) porque cada factura contiene más líneas o más unidades; (iii) porque desaparecieron las facturas pequeñas —el denominador cayó 3.98 %, y si las que se perdieron eran las de menor importe, el promedio sube sin que ninguna factura individual haya cambiado; (iv) porque la mezcla se desplazó hacia productos caros.

Concluir «subieron los precios» a partir del ticket es exactamente el salto que el laboratorio busca impedir. Y cuando el puente se calcula, la conclusión resulta ser la contraria: **el efecto precio es negativo, −£ 115 918.44**. En promedio, la empresa cobró **menos** por cada producto del catálogo común, no más. El ticket subió por mezcla y por composición de facturas, nunca por precio.

> **Formulación correcta de la afirmación.** «El ticket promedio aumentó 6.76 %. Esa variación aún no está explicada: puede provenir de precio, de mezcla, de unidades por factura o de la desaparición de facturas pequeñas. Para separar esas fuentes se requiere la descomposición del Bloque 3.»

# **BLOQUE 3 — Puente precio-volumen-mezcla**

Este es el núcleo del laboratorio. El marco formal completo está desarrollado en la sección «Marco formal del puente precio-volumen-mezcla» de este solucionario; aquí se aplica.

Tres precisiones que el docente debe verbalizar antes de ejecutar las celdas:

1. **El precio que se usa es el precio efectivo**, $p_{ti} = r_{ti}/q_{ti}$, no el de lista. Absorbe descuentos, escalas por volumen y precios negociados: es lo que la empresa realmente cobró.
2. **La descomposición solo se aplica al catálogo común**, porque un producto sin contraparte en el otro periodo no tiene precio de comparación.
3. **El orden de los efectos importa.** Cada uno se calcula manteniendo fijo lo que ya se aisló. Otra secuencia produciría otro reparto igualmente válido; por eso se declara la que se usa.

In [12]:
# Calculamos las unidades y el precio efectivo de cada producto en cada periodo
## El precio efectivo representa lo que realmente se cobró por unidad

por_producto = (
    comparables
    .group_by(["periodo", "codigo"])  ## Agrupamos por periodo y producto
    .agg(
        pl.col("cantidad").sum().alias("q"),  ## Sumamos las unidades vendidas
        pl.col("ingreso").sum().alias("r")  ## Sumamos los ingresos generados
    )
    .with_columns(
        (pl.col("r") / pl.col("q")).alias("p")  ## Calculamos el precio efectivo: ingreso / unidades
    )
)

# Separamos la información de P0 y P1 para poder compararlos
p0 = por_producto.filter(pl.col("periodo") == "P0").drop("periodo")  ## Datos del periodo base
p1 = por_producto.filter(pl.col("periodo") == "P1").drop("periodo")  ## Datos del periodo final

# Mostramos cuántos productos existen en cada periodo
print("Productos en P0:", p0.height, "   Productos en P1:", p1.height)

Productos en P0: 4220    Productos en P1: 3904


### **Productos por periodo**

En P0 se identificaron **4,220 productos**, mientras que en P1 se identificaron **3,904 productos**.

Esto representa una reducción de **316 productos (-7.49 %)** entre ambos periodos. Por lo tanto, el catálogo utilizado en P1 es menor que el de P0.

Para el puente precio-volumen-mezcla, esta diferencia es importante porque la descomposición se realizará sobre el **catálogo común**, es decir, únicamente sobre los productos presentes en ambos periodos.

In [13]:
# Separamos los productos según su presencia en P0 y P1
## El catálogo común permite calcular precio, volumen y mezcla de forma comparable
## Los productos nuevos y discontinuados se cuantifican aparte para mantener la reconciliación

comun = p0.join(p1, on="codigo", suffix="_1")  ## Productos presentes en ambos periodos

discontinuados = p0.join(p1, on="codigo", how="anti")  ## Productos vendidos en P0 pero no en P1

nuevos = p1.join(p0, on="codigo", how="anti")  ## Productos vendidos en P1 pero no en P0

# Mostramos el tamaño y los ingresos asociados a cada grupo
print(f"Catálogo común  : {comun.height:>5} productos")  ## Productos comparables entre P0 y P1

print(f"Discontinuados  : {discontinuados.height:>5} productos   "
      f"£ {discontinuados['r'].sum():>14,.2f}")  ## Ingresos de productos que dejaron de venderse

print(f"Nuevos en P1    : {nuevos.height:>5} productos   "
      f"£ {nuevos['r'].sum():>14,.2f}")  ## Ingresos de productos que aparecieron en P1

Catálogo común  :  3230 productos
Discontinuados  :   990 productos   £     704,357.16
Nuevos en P1    :   674 productos   £   2,046,903.92


### **Catálogo común, discontinuados y nuevos**

El **catálogo común** está compuesto por **3,230 productos**, que son los que pueden compararse directamente entre P0 y P1.

En P0 dejaron de venderse **990 productos discontinuados**, que representaban **£704,357.16** en ingresos. Por otro lado, en P1 aparecieron **674 productos nuevos**, que generaron **£2,046,903.92**.

Esto muestra que el cambio del catálogo fue importante: **los productos nuevos generaron muchos más ingresos que los productos discontinuados**. Por eso, estos grupos deben mantenerse separados del cálculo de precio-volumen-mezcla del catálogo común.

In [14]:
# Realizamos la descomposición precio-volumen-mezcla sobre el catálogo común
## Solo usamos productos presentes en P0 y P1 para asegurar una comparación válida

# Calculamos el volumen total de unidades del catálogo común en cada periodo
Q0 = comun["q"].sum()  ## Volumen total del catálogo común en P0
Q1 = comun["q_1"].sum()  ## Volumen total del catálogo común en P1

# Calculamos la participación de cada producto dentro del volumen de su periodo
c = comun.with_columns(
    (pl.col("q") / Q0).alias("s0"),  ## Participación del producto en P0
    (pl.col("q_1") / Q1).alias("s1")  ## Participación del producto en P1
)

# Calculamos el efecto volumen
## Mide cuánto cambia el ingreso por vender más o menos unidades
## manteniendo como referencia los precios y la composición de P0
efecto_volumen = (Q1 - Q0) * (c["s0"] * c["p"]).sum()

# Calculamos el efecto mezcla
## Mide el impacto del cambio en la composición de productos
## manteniendo constantes los precios efectivos de P0
efecto_mezcla = Q1 * ((c["s1"] - c["s0"]) * c["p"]).sum()

# Calculamos el efecto precio
## Mide el impacto del cambio en los precios efectivos de los productos
## utilizando la composición observada en P1
efecto_precio = Q1 * (c["s1"] * (c["p_1"] - c["p"])).sum()

# Calculamos la variación real del ingreso del catálogo común
variacion_comun = c["r_1"].sum() - c["r"].sum()  ## Ingreso P1 menos ingreso P0

# Sumamos los tres efectos para comprobar la reconciliación
suma_efectos = efecto_volumen + efecto_mezcla + efecto_precio  ## Volumen + mezcla + precio

# Mostramos cada componente y comprobamos que la suma coincida con la variación real
print(f"Efecto volumen : £ {efecto_volumen:>14,.2f}")
print(f"Efecto mezcla  : £ {efecto_mezcla:>14,.2f}")
print(f"Efecto precio  : £ {efecto_precio:>14,.2f}")
print(f"{'-' * 34}")
print(f"Suma           : £ {suma_efectos:>14,.2f}")  ## Suma de los tres efectos
print(f"Variación real : £ {variacion_comun:>14,.2f}")  ## Variación real del catálogo común
print(f"Diferencia     : £ {variacion_comun - suma_efectos:>14,.2f}")  ## Debe ser 0 para validar la reconciliación

Efecto volumen : £  -1,568,093.05
Efecto mezcla  : £     577,550.82
Efecto precio  : £    -115,918.44
----------------------------------
Suma           : £  -1,106,460.66
Variación real : £  -1,106,460.66
Diferencia     : £           0.00


### **Descomposición precio-volumen-mezcla**

El **efecto volumen** fue de **−£1,568,093.05**, mostrando que la reducción de unidades tuvo un impacto negativo importante sobre los ingresos.

El **efecto mezcla** fue de **+£577,550.82**, lo que indica que el cambio en la composición de los productos compensó parcialmente la pérdida de volumen.

El **efecto precio** fue de **−£115,918.44**, por lo que los cambios en los precios efectivos también tuvieron un impacto negativo.

La suma de los tres efectos fue **−£1,106,460.66**, exactamente igual a la **variación real de −£1,106,460.66**. La **diferencia de £0.00 confirma que la descomposición reconcilia correctamente**.

En conclusión, dentro del catálogo común, el **volumen fue el principal efecto negativo**, mientras que la **mezcla compensó una parte importante de la caída**.

In [15]:
# Comprobamos que la descomposición de ingresos sea correcta
## Si los efectos no coinciden con la variación observada, el análisis debe detenerse

assert abs(variacion_comun - suma_efectos) < 0.01, "Los efectos no reconcilian"  ## Verificamos el catálogo común

# Calculamos la variación total de ingresos entre P0 y P1
variacion_total = p1["r"].sum() - p0["r"].sum()  ## Ingreso total de P1 menos ingreso total de P0

# Reconstruimos la variación total incluyendo productos nuevos y discontinuados
reconstruida = variacion_comun + nuevos["r"].sum() - discontinuados["r"].sum()

assert abs(variacion_total - reconstruida) < 0.01, "El puente completo no reconcilia"  ## Verificamos el puente completo

# Mostramos los resultados de la reconciliación
print("Reconciliación verificada.")

print(f"\nVariación total de ingresos : £ {variacion_total:,.2f}")  ## Variación total entre P0 y P1
print(f"  Catálogo común            : £ {variacion_comun:,.2f}")  ## Variación explicada por productos comunes
print(f"    · efecto volumen        : £ {efecto_volumen:,.2f}")  ## Impacto del cambio en unidades
print(f"    · efecto mezcla         : £ {efecto_mezcla:,.2f}")  ## Impacto del cambio en la composición
print(f"    · efecto precio         : £ {efecto_precio:,.2f}")  ## Impacto del cambio en precios efectivos
print(f"  Productos nuevos          : £ {nuevos['r'].sum():,.2f}")  ## Ingresos aportados por productos nuevos
print(f"  Productos discontinuados  : £ {-discontinuados['r'].sum():,.2f}")  ## Ingresos perdidos por productos discontinuados

Reconciliación verificada.

Variación total de ingresos : £ 236,086.10
  Catálogo común            : £ -1,106,460.66
    · efecto volumen        : £ -1,568,093.05
    · efecto mezcla         : £ 577,550.82
    · efecto precio         : £ -115,918.44
  Productos nuevos          : £ 2,046,903.92
  Productos discontinuados  : £ -704,357.16


### **Reconciliación completa de los ingresos**

La variación total de ingresos entre P0 y P1 fue de **+£236,086.10**.

El **catálogo común** tuvo una variación negativa de **−£1,106,460.66**, explicada por un efecto volumen de **−£1,568,093.05**, un efecto mezcla positivo de **+£577,550.82** y un efecto precio negativo de **−£115,918.44**.

Los **productos nuevos aportaron +£2,046,903.92**, mientras que los **productos discontinuados representaron −£704,357.16**. Al combinar estos componentes se obtiene exactamente la variación total de **+£236,086.10**.

La **reconciliación fue verificada correctamente**, por lo que el puente completo no presenta diferencias y las cifras pueden utilizarse para el diagnóstico.

In [16]:
# Creamos un gráfico de cascada para explicar cómo se pasa de los ingresos de P0 a los ingresos de P1
## El gráfico muestra visualmente cuánto aporta o resta cada componente de la variación

figura = go.Figure(go.Waterfall(
    orientation="v",  ## Definimos las barras en orientación vertical

    measure=[
        "absolute",  ## El ingreso inicial de P0 es un valor absoluto
        "relative",  ## Volumen modifica el valor anterior
        "relative",  ## Mezcla modifica el subtotal anterior
        "relative",  ## Precio modifica el subtotal anterior
        "relative",  ## Los productos nuevos agregan ingresos
        "relative",  ## Los productos discontinuados restan ingresos
        "total"      ## El ingreso final de P1 representa el total
    ],

    x=[
        "Ingresos P0",        ## Punto de partida del puente
        "Volumen",            ## Impacto de vender más o menos unidades
        "Mezcla",             ## Impacto del cambio en la composición de productos
        "Precio",             ## Impacto del cambio en los precios efectivos
        "Productos nuevos",   ## Ingresos generados por productos nuevos
        "Discontinuados",     ## Ingresos que se pierden por productos discontinuados
        "Ingresos P1"         ## Punto final del puente
    ],

    y=[
        p0["r"].sum(),          ## Ingresos totales del periodo P0
        efecto_volumen,         ## Efecto negativo o positivo del cambio de volumen
        efecto_mezcla,          ## Efecto del cambio en la composición del catálogo
        efecto_precio,          ## Efecto del cambio en los precios efectivos
        nuevos["r"].sum(),      ## Ingresos aportados por los productos nuevos
        -discontinuados["r"].sum(),  ## Restamos los ingresos de productos discontinuados
        p1["r"].sum()           ## Ingresos totales observados en P1
    ],

    text=[
        f"£ {v:,.0f}" for v in
        [
            p0["r"].sum(),          ## Mostramos el ingreso inicial
            efecto_volumen,         ## Mostramos el efecto volumen
            efecto_mezcla,          ## Mostramos el efecto mezcla
            efecto_precio,          ## Mostramos el efecto precio
            nuevos["r"].sum(),      ## Mostramos el aporte de productos nuevos
            -discontinuados["r"].sum(),  ## Mostramos la pérdida por discontinuados
            p1["r"].sum()            ## Mostramos el ingreso final
        ]
    ],  ## Convertimos cada valor en texto expresado en libras

    textposition="outside",  ## Colocamos los valores fuera de las barras para facilitar su lectura

    connector={
        "line": {
            "color": "#9AA7B4"
        }
    },  ## Conectamos las barras para mostrar cómo cada efecto modifica el subtotal
))

# Configuramos la presentación del gráfico
figura.update_layout(
    title="Puente de ingresos: de P0 a P1",  ## Título del gráfico
    yaxis_title="Ingresos (£)",              ## Nombre del eje vertical
    height=520,                              ## Definimos la altura del gráfico
    showlegend=False                        ## Ocultamos la leyenda porque las etiquetas ya identifican cada barra
)

# Mostramos el gráfico final
figura.show()  ## Visualizamos el puente completo de ingresos

### **Puente de ingresos de P0 a P1**

Los ingresos aumentaron de **£9,396,642 en P0 a £9,632,728 en P1**, lo que representa una variación positiva de aproximadamente **£236,086**.

El principal efecto negativo fue el **volumen**, que redujo los ingresos en **£1,568,093**. Sin embargo, el efecto **mezcla aportó £577,551**, mientras que el efecto **precio restó £115,918**. Esto muestra que la disminución de unidades vendidas tuvo un impacto importante y que el cambio en la composición de productos ayudó a compensarlo.

Los **productos nuevos fueron el mayor aporte positivo**, generando **£2,046,904**, mientras que los productos **discontinuados restaron £704,357**. Finalmente, al combinar todos estos efectos se llega a **£9,632,728 en P1**, coincidiendo con los ingresos observados.

En conclusión, el crecimiento de ingresos **no se explica por vender más unidades ni por un aumento general de precios**. El resultado positivo se consiguió principalmente gracias a los **productos nuevos y al cambio de mezcla**, que compensaron la pérdida de volumen y los productos discontinuados.

## ✅ Pregunta 4 — Lectura del puente
**a) ¿Cuál de los cinco componentes tiene mayor magnitud absoluta y de cuánto es?**

El componente de mayor magnitud absoluta es el de **productos nuevos, con +£ 2 046 903.92**, que representa el **40.8 %** de la suma de magnitudes de los cinco componentes. El segundo es el **efecto volumen del catálogo común, con −£ 1 568 093.05** (31.3 %). El orden completo, tal como lo entrega el cuadro de drivers, es:

| Orden | Componente | Contribución (£) | Peso sobre la suma de magnitudes |
|---:|---|---:|---:|
| 1 | Productos nuevos | +2 046 903.92 | 40.8 % |
| 2 | Volumen del catálogo común | −1 568 093.05 | 31.3 % |
| 3 | Productos discontinuados | −704 357.16 | 14.1 % |
| 4 | Mezcla del catálogo común | +577 550.82 | 11.5 % |
| 5 | Precio del catálogo común | −115 918.44 | 2.3 % |

La observación decisiva es que **el mayor componente, £ 2.05 millones, es 8.7 veces más grande que la variación neta que se pretende explicar, £ 236 086**. Los efectos no se suman en la misma dirección: se **compensan** entre sí. Un resultado neto pequeño no es sinónimo de un año tranquilo; aquí esconde movimientos internos por más de £ 2.26 millones en el catálogo común y £ 2.75 millones en altas y bajas de referencias.

**b) El efecto mezcla resultó positivo. ¿Qué significa en términos de qué productos se vendieron?**

Significa que, **dentro del catálogo común y sin que ningún precio se moviera**, la composición de las unidades vendidas se desplazó hacia productos de mayor precio unitario. Numéricamente: si en P1 se hubiera vendido la misma cantidad total de unidades (4 204 346) con la mezcla de P1 pero a los precios de P0, el precio medio ponderado habría sido **£ 1.831853** en lugar de los **£ 1.694483** de P0. Esa diferencia de **+£ 0.13737 por unidad**, multiplicada por las 4 204 346 unidades del catálogo común en P1, arroja exactamente los **+£ 577 550.82** del efecto mezcla.

En lenguaje comercial: **el peso relativo de las referencias caras aumentó y el de las baratas disminuyó**. Lo relevante es que esto no es una decisión de precios, sino un cambio en qué compran los clientes o en qué ofrece la empresa. Para un mayorista de artículos de regalo suele reflejar un desplazamiento del surtido de bajo valor —bolsas, envoltorios, artículos de un solo uso— hacia líneas de mayor valor unitario, como los artículos decorativos de mayor tamaño.

**c) ¿Por qué la comprobación de reconciliación es obligatoria y no un adorno?**

Por cuatro razones, todas de orden práctico:

1. **Es la única prueba de que la descomposición está completa.** Si los efectos no suman la variación observada, existe un factor no modelado. La diferencia obtenida aquí es **£ 0.00**, dentro de una tolerancia de un céntimo.
2. **Detecta errores silenciosos de código.** Un `join` que descarta filas sin avisar, una participación mal normalizada o un producto contado dos veces no producen ningún mensaje de error: producen una cifra plausible y equivocada. El `assert` es el único mecanismo que convierte ese error silencioso en una interrupción visible.
3. **Es lo primero que audita un tercero.** En un comité de gerencia, la primera pregunta ante una descomposición es «¿suma?». Un puente que no cierra descalifica al analista antes de que pueda explicar su método.
4. **Obliga a declarar los residuos en lugar de esconderlos.** La tentación habitual es crear una categoría «otros» que absorba el descuadre. Aquí no hay «otros»: hay cinco componentes definidos y la suma es exacta.

> **Consigna para la clase.** Si el `assert` falla, **el diagnóstico no se publica**. Es preferible que el notebook se detenga a que entregue una cifra falsa con apariencia de rigor.

# **RETO 1 — La métrica que describe frente a la que explica**

## ✅ Pregunta 5 — Métrica de vanidad

**a) ¿Por qué «los ingresos crecieron 2.5 %» es una métrica de vanidad en este caso?**

Una **métrica de vanidad** es un indicador que se ve bien, es técnicamente correcto y **no cambia ninguna decisión**, porque agrega tanto que oculta los movimientos que sí importan. Ese es exactamente el papel del +2.51 % aquí, por cinco motivos concretos:

1. **Es un neto de movimientos mucho mayores que se compensan.** Los £ 236 086 de crecimiento son el saldo de componentes que suman £ 5.01 millones en magnitud absoluta. La cifra neta es **veintiuna veces más pequeña** que el movimiento real que la produjo.
2. **Oculta una caída severa en el negocio histórico.** El catálogo común, que es el surtido que la empresa venía vendiendo, perdió **£ 1 106 460.66**, es decir, un **12.73 %** de sus ingresos de P0. Esa caída queda tapada por los productos nuevos.
3. **Contradice el indicador físico.** Las unidades cayeron 6.72 % y las facturas 3.98 %. Un negocio que crece en libras mientras se contrae en piezas y en pedidos no está creciendo del modo que la cifra sugiere.
4. **No indica ninguna acción.** Saber que se creció 2.5 % no dice qué hacer el lunes. Saber que el volumen del catálogo común cayó £ 1.57 millones sí lo dice: hay que revisar qué pasó con ese surtido.
5. **Genera falsa confianza.** Es la peor consecuencia. Si el comité cierra la reunión con «crecimos 2.5 %», no investigará la pérdida de volumen, y el año siguiente, cuando los productos nuevos dejen de ser nuevos, la caída aflorará sin amortiguación.

**b) Métrica alternativa, calculable con estos datos, que sí sea accionable**

Se propone un conjunto de cuatro métricas —una sola rara vez basta— ordenadas por utilidad para la gerencia comercial:

| Métrica accionable | Fórmula | Valor en el caso | Decisión que habilita |
|---|---|---:|---|
| **Variación del ingreso a catálogo constante** | $\Delta R^{\text{común}} / R_0^{\text{común}}$ | **−12.73 %** (−£ 1 106 461 sobre £ 8 692 285) | Mide el negocio sin el maquillaje de las altas de catálogo. Es el verdadero termómetro del surtido histórico. |
| **Dependencia de productos nuevos** | $R_1^{\text{nuevos}} / R_1$ | **21.25 %** | Cuantifica cuánto del ingreso del año descansa en referencias sin historia. Un 21 % obliga a preguntar qué pasará cuando dejen de ser novedad. |
| **Variación del volumen del catálogo común** | $(Q_1-Q_0)/Q_0$ | **−18.04 %** | Es el indicador físico, inmune a los efectos de precio y mezcla. Señala directamente pérdida de demanda o de disponibilidad. |
| **Retención al mes 6 por cohorte** | $\text{Ret}_c(6)$ | **19.24 %** (cohortes del primer año) frente a **15.66 %** (del segundo) | Mide la calidad de los clientes captados y anticipa el ingreso del año siguiente. |

La primera es la que se recomienda llevar al comité como titular, porque responde con una sola cifra a la pregunta que la gerencia realmente tiene: **«quitando los productos nuevos, ¿el negocio creció o se contrajo?» — se contrajo 12.73 %.**

# **BLOQUE 4 — Cohortes y curvas de retención**

El puente explicó la variación desde el lado del **producto**. Este bloque la examina desde el lado del **cliente**.

**Advertencia de alcance que debe declararse en el informe.** Las cohortes se construyen únicamente sobre los **5 852 clientes identificados**. El 22.77 % de las líneas sin identificador queda fuera por necesidad metodológica, no por conveniencia: sin identificador no hay a quién seguir. En consecuencia, toda conclusión sobre retención describe al subconjunto identificado y no necesariamente a la totalidad de los compradores.

**Advertencia de truncamiento.** El archivo termina el 9 de diciembre de 2011. Por lo tanto:

- La cohorte de **noviembre de 2011** tiene como mes 1 un diciembre de apenas nueve días: su 14.1 % de retención está **mecánicamente subestimado** y no debe compararse con el de ninguna otra cohorte.
- Las cohortes nacidas después de junio de 2011 **no alcanzan el mes 6**, y sus celdas vacías significan *aún no observado*, nunca *abandonaron*.

**Cómo se lee correctamente una matriz de cohortes.** En diagonal, no en vertical. Cada fila es una cohorte y cada columna una antigüedad; comparar dos celdas solo es legítimo si están en la **misma columna** (misma antigüedad) y ambas corresponden a cohortes que efectivamente vivieron ese mes.

In [17]:
# Construcción de cohortes de clientes
## Una cohorte agrupa clientes según el mes de su primera compra.

clientes = (
    validas
    .filter(pl.col("cliente_id").is_not_null())  ## Conservamos únicamente clientes identificados para poder hacer seguimiento
    .with_columns(
        pl.col("fecha")
        .dt.truncate("1mo")  ## Convertimos cada fecha al inicio de su mes correspondiente
        .dt.date()  ## Convertimos el resultado a formato fecha
        .alias("mes")  ## Guardamos el mes de cada compra en una nueva columna
    )
)

# Identificamos el mes de la primera compra de cada cliente
## Ese primer mes determina la cohorte a la que pertenece el cliente.

clientes = clientes.with_columns(
    pl.col("mes").min().over("cliente_id").alias("cohorte")  ## Encontramos el primer mes de compra de cada cliente
)

# Calculamos la antigüedad de cada cliente desde su primera compra
## La antigüedad nos permite comparar clientes de diferentes cohortes usando los mismos meses de seguimiento.

clientes = clientes.with_columns(
    (
        (pl.col("mes").dt.year() - pl.col("cohorte").dt.year()) * 12  ## Convertimos la diferencia de años a meses
        + (pl.col("mes").dt.month() - pl.col("cohorte").dt.month())  ## Sumamos la diferencia entre los meses
    ).alias("antiguedad")  ## Guardamos la cantidad de meses desde la primera compra
)

# Mostramos la cantidad de clientes identificados
## Solo podemos seguir a clientes que tienen un identificador disponible.

print("Clientes identificados :", f"{clientes['cliente_id'].n_unique():,}")  ## Contamos los clientes únicos identificados

# Mostramos la cantidad de cohortes mensuales
## Cada mes diferente de primera compra representa una cohorte.

print("Cohortes mensuales     :", clientes["cohorte"].n_unique())  ## Contamos las cohortes existentes

# Mostramos algunos registros para comprobar que la construcción sea correcta
## Revisamos cliente, mes de compra, cohorte y antigüedad antes de continuar con el análisis.

print(
    clientes.select(
        "cliente_id", "mes", "cohorte", "antiguedad"  ## Seleccionamos las columnas necesarias para validar el resultado
    ).head(5)  ## Mostramos los primeros 5 registros
)

Clientes identificados : 5,852
Cohortes mensuales     : 25
shape: (5, 4)
┌────────────┬────────────┬────────────┬────────────┐
│ cliente_id ┆ mes        ┆ cohorte    ┆ antiguedad │
│ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64        ┆ date       ┆ date       ┆ i32        │
╞════════════╪════════════╪════════════╪════════════╡
│ 16904      ┆ 2011-08-01 ┆ 2010-10-01 ┆ 10         │
│ 15794      ┆ 2009-12-01 ┆ 2009-12-01 ┆ 0          │
│ 12705      ┆ 2011-05-01 ┆ 2010-06-01 ┆ 11         │
│ 17841      ┆ 2010-03-01 ┆ 2009-12-01 ┆ 3          │
│ 14766      ┆ 2010-06-01 ┆ 2010-06-01 ┆ 0          │
└────────────┴────────────┴────────────┴────────────┘


### **Construcción de las cohortes de clientes**

El análisis identificó **5,852 clientes** con identificador disponible y **25 cohortes mensuales**. Esto significa que podemos realizar seguimiento de los clientes identificados según el mes en que realizaron su primera compra.

Los registros de ejemplo confirman que la **cohorte corresponde al primer mes de compra**. Por ejemplo, el cliente **15794** pertenece a la cohorte de diciembre de 2009 y tiene una antigüedad de **0 meses** en ese periodo. El cliente **17841** también pertenece a diciembre de 2009, pero realizó una compra en marzo de 2010, por lo que presenta una antigüedad de **3 meses**.

También se observa que el cliente **16904** pertenece a la cohorte de octubre de 2010 y aparece en agosto de 2011 con una antigüedad de **10 meses**. Esto confirma que la antigüedad se calcula desde la primera compra de cada cliente.

En conclusión, la construcción de las cohortes es correcta y ya tenemos la estructura necesaria para calcular la **retención de clientes por cohorte y por mes de antigüedad**.

In [18]:
# Calculamos la cantidad de clientes activos en cada cohorte y mes de antigüedad
## Un cliente activo es aquel que realizó al menos una compra durante ese mes.
## Contamos clientes únicos para evitar que un mismo cliente sea contado varias veces.

activos = (
    clientes
    .group_by(["cohorte", "antiguedad"])  ## Agrupamos por cohorte y por los meses transcurridos desde la primera compra
    .agg(
        pl.col("cliente_id").n_unique().alias("activos")  ## Contamos cuántos clientes únicos siguieron comprando
    )
)

# Calculamos el tamaño inicial de cada cohorte
## La antigüedad 0 representa el mes en que los clientes realizaron su primera compra.
## Esta cantidad será la base que utilizaremos para calcular la tasa de retención.

tamano_inicial = (
    activos
    .filter(pl.col("antiguedad") == 0)  ## Nos quedamos únicamente con los clientes del mes inicial
    .select(
        "cohorte",
        pl.col("activos").alias("inicial")  ## Guardamos el número inicial de clientes de cada cohorte
    )
)

# Calculamos la tasa de retención de cada cohorte
## La retención indica qué porcentaje de los clientes iniciales continuó comprando en cada mes.
## La fórmula es: clientes activos del mes / clientes iniciales × 100.

retencion = (
    activos
    .join(
        tamano_inicial,
        on="cohorte"
    )  ## Unimos cada cantidad de clientes activos con el tamaño inicial de su cohorte
    .with_columns(
        (100 * pl.col("activos") / pl.col("inicial")).alias("tasa")  ## Calculamos el porcentaje de clientes que permanecen activos
    )
    .sort(
        ["cohorte", "antiguedad"]
    )  ## Ordenamos las cohortes y sus meses para facilitar la lectura
)

# Construimos la matriz de retención
## Cada fila representa una cohorte y cada columna representa un mes de antigüedad.
## Esto permite comparar cohortes que tienen la misma antigüedad.

matriz = (
    retencion
    .pivot(
        values="tasa",  ## Utilizamos la tasa de retención como valor de las celdas
        index="cohorte",  ## Cada fila corresponde a una cohorte
        on="antiguedad",  ## Cada columna representa un mes desde la primera compra
        aggregate_function="first"  ## Tomamos el primer valor cuando existe una única combinación
    )
    .sort("cohorte")  ## Ordenamos las cohortes cronológicamente
)

# Mostramos los primeros seis meses de antigüedad
## Las columnas 0 a 5 permiten observar el comportamiento desde el mes inicial hasta el quinto mes posterior.
## Las celdas vacías significan que todavía no existe información suficiente para observar ese periodo.

print(
    matriz.select(
        ["cohorte"] + [str(i) for i in range(6)]  ## Seleccionamos la cohorte y los meses de antigüedad 0, 1, 2, 3, 4 y 5
    )
)

shape: (25, 7)
┌────────────┬─────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│ cohorte    ┆ 0   ┆ 1                  ┆ 2                  ┆ 3                  ┆ 4                  ┆ 5                  │
│ ---        ┆ --- ┆ ---                ┆ ---                ┆ ---                ┆ ---                ┆ ---                │
│ date       ┆ f64 ┆ f64                ┆ f64                ┆ f64                ┆ f64                ┆ f64                │
╞════════════╪═════╪════════════════════╪════════════════════╪════════════════════╪════════════════════╪════════════════════╡
│ 2009-12-01 ┆ 100 ┆ 35.01577287066246  ┆ 33.333333333333336 ┆ 42.48159831756046  ┆ 37.85488958990536  ┆ 35.96214511041009  │
│ 2010-01-01 ┆ 100 ┆ 21.467391304347824 ┆ 32.06521739130435  ┆ 31.52173913043478  ┆ 27.17391304347826  ┆ 30.97826086956522  │
│ 2010-02-01 ┆ 100 ┆ 23.466666666666665 ┆ 22.666666666666668 ┆ 29.333333333333332 ┆ 24.533333333333335 

### **Matriz de retención por cohortes**

La matriz muestra **25 cohortes mensuales**, y todas comienzan con una retención de **100 % en el mes 0**, porque ese es el momento en que los clientes realizan su primera compra. A partir del mes 1 podemos observar qué proporción de esos clientes volvió a comprar.

La cohorte de **diciembre de 2009** presenta uno de los comportamientos más fuertes: alcanza **35.02 % en el mes 1** y **35.96 % en el mes 5**. En cambio, otras cohortes presentan retenciones menores; por ejemplo, la cohorte de **febrero de 2010** llega a **19.73 % en el mes 5**. Esto muestra que la permanencia de los clientes no es igual entre todas las cohortes.

Las cohortes más recientes tienen valores `null` en los meses posteriores porque **todavía no existe suficiente información para observar esos periodos**. Por ejemplo, agosto de 2011 no tiene dato para el mes 5, septiembre no tiene datos desde el mes 3 y noviembre de 2011 solo tiene información hasta el mes 1. Estos valores vacíos **no significan 0 % de retención**, sino que el periodo aún no ha sido observado debido al truncamiento del archivo.

Un caso que debe tratarse con especial cuidado es la cohorte de **noviembre de 2011**, que presenta **14.14 % en el mes 1**. Este valor está mecánicamente subestimado porque el archivo termina el **9 de diciembre de 2011**, por lo que no contamos con un mes completo para observar el comportamiento de esa cohorte.

En conclusión, la matriz permite comparar correctamente la retención **por antigüedad**, no simplemente por posición vertical. Para comparar cohortes debemos observar la **misma columna**, ya que representa el mismo número de meses desde la primera compra. Esto nos permitirá posteriormente calcular y analizar las curvas de retención.

In [19]:
# Seleccionamos las columnas que representan los primeros 13 meses de antigüedad
## Esto permite visualizar la retención desde el mes 0 hasta el mes 12 sin mostrar una tabla demasiado extensa.
columnas = [str(i) for i in range(13)]  ## Creamos los nombres de las columnas correspondientes a los meses 0 a 12

tabla = matriz.select(
    ["cohorte"] + [c for c in columnas if c in matriz.columns]
)  ## Seleccionamos la cohorte y únicamente las columnas que realmente existen en la matriz


# Construimos el mapa de calor de la retención
## Cada fila representa una cohorte y cada columna representa un mes de antigüedad.
## Los colores permiten identificar rápidamente dónde la retención es mayor o menor.

figura = px.imshow(
    tabla.drop("cohorte").to_numpy(),  ## Convertimos las tasas de retención en una matriz numérica para graficarlas
    x=[f"Mes {c}" for c in tabla.columns[1:]],  ## Etiquetamos las columnas como Mes 0, Mes 1, Mes 2, etc.
    y=[str(f) for f in tabla["cohorte"].to_list()],  ## Utilizamos el mes de primera compra como nombre de cada cohorte
    color_continuous_scale="Blues",  ## Utilizamos una escala de colores para representar diferentes niveles de retención
    aspect="auto",  ## Permitimos que el gráfico adapte automáticamente el tamaño de las celdas
    labels={"color": "Retención (%)"},  ## Indicamos que la escala de colores representa el porcentaje de retención
    text_auto=".0f",  ## Mostramos el porcentaje de retención dentro de cada celda sin decimales
)


# Configuramos los títulos y dimensiones del gráfico
## Estos elementos ayudan a interpretar qué representa cada eje de la matriz.

figura.update_layout(
    title="Matriz de retención por cohorte mensual",  ## Título que indica que analizamos la retención de cada cohorte
    xaxis_title="Antigüedad",  ## El eje X muestra cuántos meses han pasado desde la primera compra
    yaxis_title="Cohorte (mes de primera compra)",  ## El eje Y identifica el mes en que cada grupo realizó su primera compra
    height=620  ## Definimos una altura suficiente para visualizar las 25 cohortes
)


# Mostramos la matriz de retención
## El mapa de calor facilita comparar visualmente la permanencia de los clientes entre cohortes.
## Las celdas vacías representan periodos que las cohortes recientes todavía no han alcanzado, no una retención de 0 %.

figura.show()  ## Visualizamos el mapa de calor final

### **Matriz de retención por cohorte mensual**

El mapa de calor muestra que todas las cohortes comienzan con **100 % de retención en el Mes 0**, ya que ese es el momento de su primera compra. A partir del Mes 1, la retención disminuye y presenta diferentes comportamientos según la cohorte.

La cohorte de **diciembre de 2009** destaca por mantener una retención relativamente alta. Por ejemplo, alcanza **50 % en el Mes 11** y **38 % en el Mes 12**. Esto indica que una parte importante de los clientes de esta cohorte continuó comprando durante un periodo prolongado.

En cambio, algunas cohortes presentan una caída más fuerte. Por ejemplo, la cohorte de **septiembre de 2010** llega a solo **5 % en el Mes 5** y **3 % en el Mes 9**, mostrando una menor permanencia de sus clientes. Esto evidencia que la retención cambia considerablemente entre cohortes.

También se observa claramente el efecto del **truncamiento del archivo**. Las cohortes más recientes tienen celdas vacías en los meses finales porque todavía no han alcanzado esas antigüedades. Por ejemplo, las cohortes de octubre y noviembre de 2011 no pueden compararse con las cohortes antiguas en meses avanzados. Estas celdas vacías **no representan una retención de 0 %**.

En conclusión, la matriz permite identificar qué cohortes mantienen mejor a sus clientes y cuáles pierden actividad rápidamente. Para realizar una comparación correcta debemos hacerlo **por la misma antigüedad**, es decir, comparar cohortes en la misma columna y no simplemente de forma vertical.

In [20]:
# Seleccionamos únicamente las cohortes que ya tienen al menos seis meses de observación
## Esto permite comparar las curvas hasta el Mes 6 sin incluir cohortes recientes incompletas.

maduras = (
    retencion
    .join(
        retencion
        .group_by("cohorte")
        .agg(
            pl.col("antiguedad").max().alias("tope")  ## Encontramos el último mes de antigüedad disponible para cada cohorte
        ),
        on="cohorte"  ## Unimos este límite con los registros originales de cada cohorte
    )
    .filter(
        (pl.col("tope") >= 6) &  ## Conservamos solo las cohortes que alcanzaron al menos seis meses
        (pl.col("antiguedad") <= 6)  ## Limitamos el análisis hasta el Mes 6 para comparar el mismo periodo
    )
    .with_columns(
        pl.col("cohorte").cast(pl.Utf8)  ## Convertimos la cohorte a texto para utilizarla como categoría en el gráfico
    )
)

# Convertimos los datos a formato compatible con Plotly y construimos las curvas de retención
## Cada línea representa una cohorte y muestra cómo cambia su retención desde el Mes 0 hasta el Mes 6.

figura = px.line(
    maduras.to_pandas(),  ## Convertimos la tabla de Polars a pandas para facilitar su uso con Plotly
    x="antiguedad",  ## El eje X representa los meses transcurridos desde la primera compra
    y="tasa",  ## El eje Y representa el porcentaje de clientes que continúa activo
    color="cohorte",  ## Cada cohorte tendrá una línea diferente para poder compararlas
    markers=True,  ## Colocamos puntos en cada mes para identificar fácilmente los valores
    labels={
        "antiguedad": "Meses desde la primera compra",  ## Nombre descriptivo del eje X
        "tasa": "Retención (%)",  ## Nombre descriptivo del eje Y
        "cohorte": "Cohorte"  ## Nombre que identifica las diferentes líneas
    }
)

# Configuramos la presentación del gráfico
## El título indica que estamos comparando la evolución de la retención entre diferentes cohortes.

figura.update_layout(
    title="Curvas de retención por cohorte",  ## Título principal del gráfico
    height=480  ## Definimos la altura para que las curvas sean fáciles de visualizar
)

# Mostramos las curvas de retención
## Todas las curvas comienzan en 100 % en el Mes 0 por definición.
## Lo importante es observar la pendiente y cómo cambia la retención durante los seis meses.

figura.show()  ## Visualizamos el gráfico final

### **Curvas de retención por cohorte**

Las curvas muestran que todas las cohortes comienzan en **100 % de retención en el Mes 0**, porque ese es el momento de su primera compra. La caída más fuerte ocurre entre el **Mes 0 y el Mes 1**, donde la mayoría de las cohortes baja aproximadamente al rango de **15 % a 30 %**.

La cohorte de **diciembre de 2009** destaca por tener una retención considerablemente mayor que las demás. Después de caer a aproximadamente **35 % en el Mes 1**, se mantiene relativamente estable y llega a **37.6 % en el Mes 6**. Esto indica que los clientes de esta cohorte tuvieron una permanencia superior.

En contraste, algunas cohortes presentan una caída mucho más pronunciada. Por ejemplo, una de las curvas llega aproximadamente a **9 % en el Mes 1** y se mantiene cerca de valores bajos durante los siguientes meses. Esto muestra que existen diferencias importantes en la capacidad de las distintas cohortes para mantener a sus clientes.

También se observa que las curvas no siempre disminuyen de forma continua. Algunas cohortes recuperan ligeramente su retención en determinados meses, porque un cliente puede volver a comprar después de haber estado inactivo en un mes anterior. Por ello, la retención mensual no debe interpretarse necesariamente como una pérdida definitiva del cliente.

En conclusión, el gráfico confirma que **la mayor pérdida de clientes ocurre durante los primeros meses después de la primera compra**, pero la intensidad de esa pérdida cambia según la cohorte. La cohorte de diciembre de 2009 presenta el mejor comportamiento al Mes 6, mientras que otras cohortes muestran una retención mucho menor.

## ✅ Pregunta 6 — Lectura de la matriz
**a) Compare la retención en el mes 1 de las cohortes del primer año con las del segundo. ¿Qué observa?**

Al mes 1 **no se observa deterioro**. El promedio de retención en el mes 1 es de **21.08 %** para las doce cohortes nacidas entre diciembre de 2009 y noviembre de 2010, y de **20.90 %** para las doce nacidas entre diciembre de 2010 y noviembre de 2011: una diferencia de 0.18 puntos porcentuales, económicamente irrelevante.

Dos precisiones importantes acompañan esa lectura:

- La cohorte **diciembre de 2009** (951 clientes, con 35.0 % al mes 1) es atípica y no debe tomarse como representativa: es la primera del archivo y absorbe a todos los clientes que ya eran compradores antes del inicio del registro. Su «primera compra» aparente es, en muchos casos, simplemente la primera compra **observada**. Este fenómeno se conoce como *censura a la izquierda* y afecta siempre a la cohorte inicial de cualquier panel.
- La cohorte **noviembre de 2011** (14.1 %) está truncada por el lado derecho: su mes 1 es un diciembre de nueve días. Compararla con cualquier otra sería inválido.

Descontadas esas dos, el primer rebote de los clientes nuevos es notablemente estable en torno al 20 %: **uno de cada cinco clientes vuelve al mes siguiente**, tanto en 2010 como en 2011.

**b) Elija dos cohortes con al menos seis meses de antigüedad y compárelas correctamente.**

Se comparan en la **misma columna de antigüedad** ($k=6$) dos cohortes que efectivamente la alcanzaron:

| Cohorte | Clientes iniciales | Activos en el mes 6 | Retención al mes 6 |
|---|---:|---:|---:|
| **Abril de 2010** | 294 | 81 | **27.6 %** |
| **Agosto de 2010** | 163 | 16 | **9.8 %** |

**Retiene mejor la cohorte de abril de 2010**, con 27.6 % frente a 9.8 %: casi el triple. La diferencia es además de magnitud suficiente para no atribuirse al azar del tamaño muestral, aunque conviene señalar que la cohorte de agosto es pequeña (163 clientes), de modo que cada cliente pesa 0.6 puntos porcentuales.

Comparación alternativa igualmente válida, útil para mostrar el contraste extremo: **diciembre de 2009** retiene **37.6 %** al mes 6 (358 de 951 clientes), la cifra más alta de todo el conjunto, frente a **diciembre de 2010** con **5.3 %** (4 de 76 clientes), la más baja. Aquí sí debe advertirse que la cohorte de diciembre de 2010 tiene solo 76 clientes iniciales: un movimiento de tres o cuatro personas cambia la cifra varios puntos, por lo que es una comparación ilustrativa pero frágil.

Tomando el conjunto completo de las 19 cohortes que alcanzaron el mes 6, la media pasa de **19.24 %** (las 12 cohortes del primer año) a **15.66 %** (las 7 del segundo): un deterioro de **3.6 puntos porcentuales**, equivalente a perder cerca de un **19 %** de la capacidad de retención a medio plazo. Ese sí es un hallazgo diagnóstico, y no lo era el del mes 1.

**c) ¿Por qué no puede concluirse de esta matriz que la calidad del servicio empeoró?**

Porque la matriz mide **qué pasó**, no **por qué pasó**, y existen al menos seis explicaciones alternativas plenamente compatibles con esas mismas cifras:

1. **Cambio en la mezcla de captación.** Si en el segundo año se captó a través de canales que atraen compradores más ocasionales —un marketplace, una campaña de descuento—, la retención baja sin que el servicio haya cambiado en absoluto. Los datos no contienen el canal de captación.
2. **Composición de mercados.** El segundo periodo incorpora clientes de mercados nuevos (Australia multiplica por 4.65 sus ingresos, Japón por 6.67, Noruega por 4.85). Un comprador de otro continente tiene una frecuencia de recompra estructuralmente distinta, y eso es composición, no calidad.
3. **Efecto del catálogo.** Se retiraron 990 referencias. Si un cliente compraba precisamente una de ellas, puede haber dejado de comprar por falta de producto, no por insatisfacción con el servicio.
4. **Tamaño de cohorte y azar.** Las cohortes del segundo año son mucho más pequeñas (76, 72, 106, 108 clientes) que las del primero (951, 441, 375). En grupos pequeños, la varianza aleatoria es alta.
5. **Estacionalidad no controlada.** No es lo mismo el mes 6 de una cohorte nacida en abril —que cae en octubre, plena temporada alta de regalos— que el de una nacida en junio, que cae en diciembre con el archivo truncado.
6. **Ausencia total de la variable «servicio».** Este es el argumento definitivo: el conjunto **no contiene ningún indicador de calidad de servicio**. No hay reclamos, ni tiempos de entrega, ni devoluciones por defecto, ni encuestas de satisfacción, ni rotura de stock. Afirmar que el servicio empeoró es hablar de una variable que no fue medida.

> **Redacción correcta de la conclusión.** «La retención al mes 6 se deterioró de 19.24 % a 15.66 % entre las cohortes del primer y del segundo año. Este análisis localiza el deterioro pero no identifica su causa; para atribuirlo a la calidad del servicio se requeriría incorporar datos de reclamos, tiempos de entrega y disponibilidad de stock, y comparar cohortes captadas por el mismo canal y en el mismo mercado.»

# **BLOQUE 5 — Segmentación, driver dominante y tablero**

La segmentación localiza **dónde** se concentra el movimiento. Se examinan dos dimensiones: el país del cliente y su condición de nuevo o recurrente.

**El criterio de priorización es la contribución absoluta en libras, no la variación porcentual.** La razón es aritmética: el porcentaje se calcula sobre la base del propio segmento, de modo que una base pequeña produce porcentajes espectaculares con importes irrelevantes. En este conjunto hay 43 mercados; cinco de ellos —Tailandia, Nigeria, Corea, Indias Occidentales y Bermudas— caen **−100 %** porque simplemente dejaron de registrar ventas, y entre los cinco suman £ 6 091.17, menos del 0.07 % de los ingresos del periodo base.

In [21]:
# Segmentación explicativa por país
## Buscamos identificar qué países explican una mayor cantidad de ingresos perdidos o ganados.
## También calculamos el cambio porcentual para saber qué países se deterioraron más respecto a su propio tamaño.

por_pais = (
    comparables
    .group_by(["pais", "periodo"])  ## Agrupamos las ventas por país y por periodo P0 o P1
    .agg(
        pl.col("ingreso").sum()  ## Sumamos los ingresos de cada país en cada periodo
    )
    .pivot(
        values="ingreso",  ## Utilizamos el ingreso como valor que queremos comparar
        index="pais",  ## Cada fila representa un país
        on="periodo",  ## Creamos una columna para P0 y otra para P1
        aggregate_function="first"  ## Tomamos el único valor resultante para cada país y periodo
    )
    .fill_null(0.0)  ## Si un país no tiene ingresos en alguno de los periodos, colocamos 0
    .with_columns(
        (pl.col("P1") - pl.col("P0")).alias("variacion")  ## Calculamos cuánto aumentó o disminuyó el ingreso en libras
    )
    .with_columns(
        pl.when(pl.col("P0") > 0)  ## Verificamos que el ingreso inicial sea mayor que cero antes de calcular el porcentaje
          .then(
              100 * pl.col("variacion") / pl.col("P0")  ## Calculamos la variación porcentual respecto a P0
          )
          .otherwise(None)  ## Si P0 es cero, evitamos una división entre cero
          .alias("variacion_pct")  ## Guardamos el resultado como variación porcentual
    )
    .sort("variacion")  ## Ordenamos desde las mayores caídas hasta los mayores aumentos
)

# Mostramos los países con las mayores caídas de ingresos
## Al ordenar por "variacion", los valores más negativos aparecen primero.
## Estos países son los que más ingresos perdieron en términos absolutos.

print("Mayores caídas en libras:")
print(por_pais.head(6))  ## Mostramos los 6 países con mayor pérdida absoluta


# Mostramos los países con los mayores aumentos de ingresos
## Los valores positivos más altos aparecen al final de la tabla porque está ordenada de menor a mayor.

print("\nMayores aumentos en libras:")
print(por_pais.tail(6))  ## Mostramos los 6 países con mayor aumento absoluto


# La variación absoluta y porcentual deben analizarse juntas
## Una caída de -70 % no necesariamente representa un problema grande si el país tenía pocos ingresos.
## Por eso, primero priorizamos el impacto absoluto en libras y luego usamos el porcentaje como señal complementaria.

Mayores caídas en libras:
shape: (6, 5)
┌──────────────────────┬────────────────────┬────────────────────┬─────────────────────┬────────────────────┐
│ pais                 ┆ P0                 ┆ P1                 ┆ variacion           ┆ variacion_pct      │
│ ---                  ┆ ---                ┆ ---                ┆ ---                 ┆ ---                │
│ str                  ┆ f64                ┆ f64                ┆ f64                 ┆ f64                │
╞══════════════════════╪════════════════════╪════════════════════╪═════════════════════╪════════════════════╡
│ EIRE                 ┆ 352563.3000000051  ┆ 263709.9699999998  ┆ -88853.33000000531  ┆ -25.20209278731054 │
│ Denmark              ┆ 49211.35000000003  ┆ 18060.439999999995 ┆ -31150.910000000033 ┆ -63.30025492086686 │
│ Sweden               ┆ 49490.30999999994  ┆ 36590.83000000004  ┆ -12899.479999999901 ┆ -26.06465790980076 │
│ Greece               ┆ 14285.670000000016 ┆ 3879.529999999999  ┆ -10406.140000

### **Segmentación de ingresos por país**

Las mayores caídas en términos absolutos se concentran principalmente en **EIRE**, que pasó de **£352,563.30 a £263,709.97**, representando una pérdida de **£88,853.33 (−25.20 %)**. Le siguen **Dinamarca**, con **−£31,150.91**, y **Suecia**, con **−£12,899.48**. Estos países son importantes porque representan pérdidas reales de ingresos, no solamente porcentajes elevados.

Por otro lado, algunos países presentan porcentajes de crecimiento muy altos, pero con una base pequeña. Por ejemplo, **Japón creció 567.25 %**, pero el aumento absoluto fue de solo **£31,808.83**. **Noruega** creció 385.38 %, pero aportó **£23,588.22** adicionales. Esto demuestra por qué no debemos utilizar únicamente la variación porcentual para decidir qué segmento priorizar.

El **Reino Unido** tuvo un crecimiento porcentual pequeño de solo **0.95 %**, pero representa un aumento absoluto de **£76,587.64**, debido al enorme tamaño de su base de ingresos. Por su parte, **Australia** tuvo el mayor aumento absoluto de los países mostrados, con **+£108,407.61**, acompañado de un crecimiento de **365.06 %**.

En conclusión, para priorizar la gestión debemos enfocarnos principalmente en el **impacto absoluto en libras**. En las caídas, **EIRE es el mercado que requiere mayor atención**, mientras que en los aumentos **Australia destaca por su contribución de +£108,407.61**. Los porcentajes sirven como complemento para entender la intensidad del cambio, pero no deben utilizarse solos para establecer prioridades.

In [22]:
# Segunda dimensión de segmentación: clientes nuevos frente a clientes recurrentes
## Buscamos identificar si los ingresos de P1 provienen de clientes que ya compraban o de clientes que compraron por primera vez.

clientes_p0 = (
    comparables
    .filter(pl.col("periodo") == "P0")  ## Nos quedamos únicamente con las compras realizadas durante P0
    ["cliente_id"]
    .unique()  ## Eliminamos clientes repetidos para obtener una sola vez cada cliente
    .to_list()  ## Convertimos los identificadores a una lista para poder utilizarlos en la clasificación
)

# Clasificamos a los clientes de P1 según si ya habían comprado durante P0
## Si el cliente aparece en P0, lo consideramos recurrente; si no aparece, lo consideramos nuevo.

tipos = (
    comparables
    .filter(
        (pl.col("periodo") == "P1") &  ## Analizamos únicamente las compras del periodo P1
        pl.col("cliente_id").is_not_null()  ## Excluimos registros sin identificador porque no podemos clasificar al cliente
    )
    .with_columns(
        pl.when(
            pl.col("cliente_id").is_in(clientes_p0)  ## Comprobamos si el cliente ya había comprado durante P0
        )
        .then(
            pl.lit("recurrente")  ## Si estaba en P0, clasificamos al cliente como recurrente
        )
        .otherwise(
            pl.lit("nuevo")  ## Si no estaba en P0, clasificamos al cliente como nuevo
        )
        .alias("tipo")  ## Guardamos la clasificación en una nueva columna llamada tipo
    )
    .group_by("tipo")  ## Agrupamos los resultados entre clientes nuevos y recurrentes
    .agg(
        pl.col("ingreso")
        .sum()
        .round(2)
        .alias("ingresos"),  ## Calculamos los ingresos totales generados por cada tipo de cliente

        pl.col("cliente_id")
        .n_unique()
        .alias("clientes")  ## Contamos cuántos clientes únicos existen en cada grupo
    )
    .with_columns(
        (
            pl.col("ingresos") / pl.col("clientes")
        )
        .round(2)
        .alias("ingreso_por_cliente")  ## Calculamos cuánto ingreso genera, en promedio, cada cliente de cada grupo
    )
)

# Mostramos la comparación entre clientes nuevos y recurrentes
## La tabla permite conocer cuántos clientes hay en cada grupo, cuánto ingreso generan y cuál es su ingreso promedio por cliente.

print(tipos)

shape: (2, 4)
┌────────────┬────────────┬──────────┬─────────────────────┐
│ tipo       ┆ ingresos   ┆ clientes ┆ ingreso_por_cliente │
│ ---        ┆ ---        ┆ ---      ┆ ---                 │
│ str        ┆ f64        ┆ u32      ┆ f64                 │
╞════════════╪════════════╪══════════╪═════════════════════╡
│ recurrente ┆ 6776786.9  ┆ 2708     ┆ 2502.51             │
│ nuevo      ┆ 1448212.66 ┆ 1585     ┆ 913.7               │
└────────────┴────────────┴──────────┴─────────────────────┘


### **Clientes nuevos frente a clientes recurrentes**

En P1 se identificaron **2,708 clientes recurrentes** y **1,585 clientes nuevos**. Los clientes recurrentes generaron **£6,776,786.90**, mientras que los clientes nuevos generaron **£1,448,212.66**.

La diferencia también se observa en el ingreso promedio por cliente. Cada cliente recurrente generó en promedio **£2,502.51**, mientras que cada cliente nuevo generó **£913.70**. Esto significa que, en promedio, un cliente recurrente generó aproximadamente **2.7 veces más ingresos** que un cliente nuevo.

Por lo tanto, los clientes recurrentes tienen un peso mucho mayor en los ingresos de P1. Esto indica que **mantener a los clientes existentes es especialmente importante para el negocio**, ya que perder clientes recurrentes podría tener un impacto considerable en los ingresos.

En conclusión, aunque los clientes nuevos aportan **£1.45 millones** y son importantes para seguir creciendo, los **clientes recurrentes son el segmento de mayor valor económico**, con **£6.78 millones** de ingresos y un ingreso promedio de **£2,502.51 por cliente**.

In [25]:
# Repetimos el análisis de segmentación por país utilizando SQL
## DuckDB permite consultar directamente el DataFrame de Polars sin necesidad de crear una base de datos.
## Esto demuestra que el mismo análisis puede realizarse tanto con Polars como con SQL.

consulta = duckdb.sql("""
    SELECT pais,  -- Seleccionamos el país para comparar los resultados por mercado

           SUM(
               CASE
                   WHEN periodo = 'P0' THEN ingreso
                   ELSE 0
               END
           ) AS p0,  -- Calculamos los ingresos correspondientes al periodo P0

           SUM(
               CASE
                   WHEN periodo = 'P1' THEN ingreso
                   ELSE 0
               END
           ) AS p1,  -- Calculamos los ingresos correspondientes al periodo P1

           SUM(
               CASE
                   WHEN periodo = 'P1' THEN ingreso
                   ELSE -ingreso
               END
           ) AS variacion,  -- Calculamos la diferencia entre los ingresos de P1 y P0

           COUNT(
               DISTINCT cliente_id
           ) AS clientes  -- Contamos los clientes únicos asociados a cada país

    FROM comparables  -- Utilizamos la tabla de transacciones comparables entre P0 y P1

    GROUP BY pais  -- Agrupamos todas las operaciones para obtener un resultado por país

    HAVING SUM(
        CASE
            WHEN periodo = 'P0' THEN ingreso
            ELSE 0
        END
    ) > 20000  -- Consideramos únicamente países que superaron £20,000 de ingresos en P0
               -- Esto evita priorizar mercados muy pequeños con variaciones porcentuales exageradas

    ORDER BY variacion  -- Ordenamos desde las mayores caídas hasta los mayores aumentos

""").pl()  ## Convertimos el resultado de DuckDB nuevamente a un DataFrame de Polars


# Mostramos el resultado de la consulta SQL
## La tabla permite identificar qué países tuvieron mayor impacto absoluto en la variación de ingresos.
## Al ordenar por "variacion", los países con pérdidas aparecen primero y los que crecieron aparecen después.

print(consulta)  ## Mostramos la tabla final obtenida mediante SQL

shape: (13, 5)
┌─────────────────┬────────────────────┬────────────────────┬─────────────────────┬──────────┐
│ pais            ┆ p0                 ┆ p1                 ┆ variacion           ┆ clientes │
│ ---             ┆ ---                ┆ ---                ┆ ---                 ┆ ---      │
│ str             ┆ f64                ┆ f64                ┆ f64                 ┆ i64      │
╞═════════════════╪════════════════════╪════════════════════╪═════════════════════╪══════════╡
│ EIRE            ┆ 352563.3000000013  ┆ 263709.96999999863 ┆ -88853.33000000007  ┆ 3        │
│ Denmark         ┆ 49211.350000000006 ┆ 18060.439999999988 ┆ -31150.91000000003  ┆ 11       │
│ Sweden          ┆ 49490.31000000001  ┆ 36590.82999999998  ┆ -12899.479999999992 ┆ 19       │
│ Channel Islands ┆ 24032.789999999983 ┆ 19799.139999999985 ┆ -4233.65            ┆ 13       │
│ Portugal        ┆ 20387.159999999996 ┆ 24534.919999999976 ┆ 4147.76000000001    ┆ 23       │
│ Netherlands     ┆ 265884.06999999

### **Segmentación por país mediante SQL**

La consulta SQL identifica **13 países** que superaron los **£20,000 de ingresos en P0**, permitiendo concentrarnos en mercados con un peso suficiente para el análisis. La mayor caída corresponde a **EIRE**, que pasó de **£352,563.30 a £263,709.97**, con una reducción de **£88,853.33**.

También presentan caídas **Dinamarca**, con **−£31,150.91**, **Suecia**, con **−£12,899.48**, y **Channel Islands**, con **−£4,233.65**. Estos mercados son los principales focos de atención porque representan pérdidas absolutas de ingresos.

En el lado positivo, **Australia** presenta el mayor aumento absoluto, con **+£108,407.61**, seguido por **Reino Unido**, con **+£76,587.64**, y **Francia**, con **+£51,356.79**. El Reino Unido destaca especialmente porque concentra **5,313 clientes** y genera la mayor cantidad de ingresos de todos los países analizados.

En conclusión, el análisis mediante SQL confirma el resultado obtenido anteriormente con Polars: **EIRE es el principal mercado que explica una caída de ingresos**, mientras que **Australia es el principal mercado que aporta crecimiento**. El filtro de £20,000 ayuda a evitar que mercados muy pequeños distorsionen la priorización.

In [26]:
# Construimos el cuadro final de drivers
## Este cuadro resume los principales componentes que explican la variación de ingresos entre P0 y P1.
## El driver dominante se determina por su magnitud absoluta en libras y no por su variación porcentual.

drivers = pl.DataFrame({
    "driver": [  ## Definimos el nombre de cada componente que participa en el puente de ingresos
        "Volumen del catálogo común",
        "Mezcla del catálogo común",
        "Precio del catálogo común",
        "Productos nuevos",
        "Productos discontinuados"
    ],
    "contribucion": [  ## Incorporamos el aporte positivo o negativo de cada driver
        efecto_volumen,
        efecto_mezcla,
        efecto_precio,
        nuevos["r"].sum(),
        -discontinuados["r"].sum()
    ],
}).with_columns(
    pl.col("contribucion").round(2),  ## Redondeamos las contribuciones a dos decimales para facilitar su lectura
    pl.col("contribucion").abs().alias("magnitud"),  ## Calculamos el valor absoluto para comparar el tamaño de cada driver sin importar su signo
).with_columns(
    (
        100 * pl.col("magnitud") / pl.col("magnitud").sum()
    )
    .round(1)
    .alias("peso_relativo"),  ## Calculamos qué porcentaje representa cada driver sobre la suma de las magnitudes
).sort(
    "magnitud",
    descending=True
).drop(
    "magnitud"
)  ## Ordenamos de mayor a menor impacto y eliminamos la columna auxiliar de magnitud


# Mostramos el cuadro final de drivers
## La tabla permite identificar rápidamente cuáles son los componentes con mayor impacto económico.

print(drivers)  ## Mostramos los cinco drivers ordenados por su magnitud absoluta


# Mostramos la variación neta total de los ingresos
## Esta cifra representa el resultado final después de compensar los efectos positivos y negativos.

print(
    f"\nVariación neta de ingresos: £ {variacion_total:,.2f}"
)  ## Mostramos cuánto cambiaron realmente los ingresos entre P0 y P1


# Explicamos cómo interpretar los cinco drivers
## La suma con signo de los cinco componentes debe coincidir con la variación neta de ingresos.
## Sin embargo, sus magnitudes individuales son mucho mayores porque existen efectos positivos y negativos que se compensan.

print(
    "Los cinco drivers suman esa variación neta, pero cada uno la supera"
)  ## Indicamos que los componentes individuales son mayores que el resultado neto

print(
    "ampliamente en magnitud: se compensan entre sí. Ese es el hallazgo."
)  ## Recordamos que el crecimiento neto oculta movimientos internos importantes

shape: (5, 3)
┌────────────────────────────┬──────────────┬───────────────┐
│ driver                     ┆ contribucion ┆ peso_relativo │
│ ---                        ┆ ---          ┆ ---           │
│ str                        ┆ f64          ┆ f64           │
╞════════════════════════════╪══════════════╪═══════════════╡
│ Productos nuevos           ┆ 2046903.92   ┆ 40.8          │
│ Volumen del catálogo común ┆ -1568093.05  ┆ 31.3          │
│ Productos discontinuados   ┆ -704357.16   ┆ 14.1          │
│ Mezcla del catálogo común  ┆ 577550.82    ┆ 11.5          │
│ Precio del catálogo común  ┆ -115918.44   ┆ 2.3           │
└────────────────────────────┴──────────────┴───────────────┘

Variación neta de ingresos: £ 236,086.10
Los cinco drivers suman esa variación neta, pero cada uno la supera
ampliamente en magnitud: se compensan entre sí. Ese es el hallazgo.


### **Cuadro final de drivers**

El driver con mayor magnitud absoluta es **Productos nuevos**, con un aporte de **+£2,046,903.92**, equivalente al **40.8 %** de la suma de magnitudes. Esto significa que fue el componente que más movimiento generó en los ingresos.

En segundo lugar aparece el **volumen del catálogo común**, con **−£1,568,093.05 (31.3 %)**. Luego están los **productos discontinuados**, con **−£704,357.16 (14.1 %)**, la **mezcla**, con **+£577,550.82 (11.5 %)**, y finalmente el **precio**, con **−£115,918.44 (2.3 %)**.

Aunque los ingresos aumentaron en términos netos **+£236,086.10**, el resultado oculta movimientos mucho mayores. Los efectos positivos y negativos se compensaron entre sí. Por ejemplo, los productos nuevos aportaron más de **£2 millones**, mientras que la pérdida de volumen del catálogo común restó más de **£1.5 millones**.

En conclusión, el **driver dominante por magnitud absoluta es Productos nuevos**, pero esto no significa que sea necesariamente la causa del crecimiento. El cuadro nos permite identificar **dónde está el mayor movimiento económico** y qué componentes deberían investigarse para tomar una decisión.

## ✅ Pregunta 7 — Priorización
**a) Identifique el país con mayor caída en libras y el país con mayor caída porcentual. ¿Son el mismo?**

**No son el mismo, y la distancia entre ambos es el punto central de la pregunta.**

| Criterio | Mercado | Cifra | Contexto |
|---|---|---:|---|
| Mayor caída **en libras** | **EIRE (Irlanda)** | **−£ 88 853.33** (−25.20 %) | Pasa de £ 352 563.30 a £ 263 709.97. Representaba el 3.75 % de los ingresos de P0. |
| Mayor caída **porcentual** | **Tailandia, Nigeria, Corea, Indias Occidentales y Bermudas** | **−100 %** cada uno | Desaparecen por completo. Entre los cinco suman £ 6 091.17, el 0.065 % de P0. |
| Mayor caída porcentual entre mercados que **siguen operando** | **Emiratos Árabes Unidos** | **−77.82 %** | Solo £ 6 543.67 de pérdida. |
| Mercado con caída **fuerte en ambas dimensiones** | **Dinamarca** | **−£ 31 150.91 y −63.30 %** | Pasa de £ 49 211.35 a £ 18 060.44 con 11 clientes. |

Si la gerencia ordenara por porcentaje, su primera prioridad sería Nigeria: un mercado que perdió **£ 112.57**. Ese es, en una sola cifra, el costo de priorizar mal.

**b) Si la gerencia solo pudiera atender un mercado, ¿cuál recomendaría y por qué?**

**Se recomienda Dinamarca, no EIRE**, y la justificación exige distinguir dos situaciones que el dato permite separar:

- **EIRE es la mayor pérdida en libras, pero es un problema de cuentas, no de mercado.** La consulta DuckDB revela el dato decisivo: EIRE opera con **3 clientes identificados** en todo el periodo. Con esa concentración, £ 88 853 de caída no describen el deterioro de una plaza, sino el comportamiento de dos o tres cuentas mayoristas —probablemente una sola que redujo sus pedidos, ya que las facturas pasan de 299 a 272 mientras el importe cae 25 %. La acción que corresponde no es una campaña comercial en Irlanda: es **una llamada del director comercial a esas cuentas**, y es una acción barata, rápida y de alta probabilidad de recuperación. Por eso, aunque es la cifra más grande, no consume el recurso escaso.
- **Dinamarca sí exhibe un patrón de mercado.** Cae 63.30 % —de £ 49 211 a £ 18 060— repartido entre **11 clientes**. Que once cuentas se contraigan simultáneamente en dos tercios no se explica por el comportamiento de una empresa: sugiere un problema estructural de la plaza (competidor local, distribuidor que cambió de proveedor, portes, plazos de entrega). Es el caso que **requiere diagnóstico de campo** y por tanto el que justifica asignar el recurso escaso.

**Regla de decisión que se desprende y conviene fijar en la pizarra:**

$$\text{Prioridad} \;=\; f\big(\underbrace{|\Delta R_g|}_{\text{cuánto dinero}},\; \underbrace{\Delta R_g/R_{0g}}_{\text{qué tan grave}},\; \underbrace{n_g}_{\text{cuántos clientes}}\big)$$

Las tres dimensiones a la vez. La primera dice cuánto está en juego; la segunda, si el mercado se está deteriorando o solo fluctuando; la tercera, si el problema es de mercado o de cuenta. **EIRE: mucho dinero, gravedad media, un solo cliente relevante → gestión de cuentas. Dinamarca: dinero significativo, gravedad alta, once clientes → intervención de mercado. Nigeria: nada de dinero → no es prioridad, aunque caiga 100 %.**

**c) ¿Qué información adicional, no contenida en este conjunto, necesitaría para sostener una afirmación causal?**

El conjunto contiene ocho columnas: factura, código, descripción, cantidad, fecha, precio, cliente y país. Con eso se puede diagnosticar, jamás demostrar causa. Se requeriría, como mínimo:

| Ámbito | Dato faltante | Qué permitiría afirmar |
|---|---|---|
| **Oferta** | Disponibilidad de stock por producto y fecha | Distinguir «el cliente no quiso comprar» de «no había producto que vender». Es la ambigüedad más grave del caso: la caída de volumen del catálogo común podría ser enteramente un problema de abastecimiento. |
| **Decisión interna** | Fecha y motivo de cada discontinuación | Distinguir causalidad inversa: ¿se retiró el producto porque no se vendía, o dejó de venderse porque se retiró? |
| **Precio** | Precio de lista frente a precio efectivo, y descuentos otorgados | Separar una rebaja deliberada de un cambio de mezcla de clientes. |
| **Demanda** | Precios y catálogo de la competencia por mercado | Atribuir la caída danesa a la entrada de un competidor. |
| **Marketing** | Canal de captación, campañas y su calendario | Explicar el deterioro de la retención de las cohortes recientes por composición de la captación. |
| **Servicio** | Reclamos, plazos de entrega, incidencias, devoluciones por defecto | Sostener cualquier afirmación sobre calidad de servicio, hoy imposible porque la variable no existe en el dato. |
| **Costos** | Costo unitario por producto | Pasar del análisis de ingreso al de margen, que es la cifra que realmente decide si conviene renovar el catálogo. |
| **Diseño** | Un experimento: retirar o mantener referencias de manera aleatoria por mercado | **Esta es la única que autoriza el verbo «causó».** Sin asignación aleatoria o un contrafactual creíble, toda afirmación causal es una hipótesis. |

---

# **Reto de aplicación y retroalimentación**

Los cinco ejercicios operan sobre las tablas `comparables`, `por_pais`, `retencion`, `matriz` y `drivers`, ya construidas durante la sesión. Cada ejercicio presenta el **código resuelto y ejecutable**, seguido de la **respuesta modelo** a su pregunta de cierre.

---

## Ejercicio 1 — Identificación y ponderación del efecto dominante

**Se solicita:** determinar cuál de los tres efectos presenta mayor valor absoluto; expresar cada efecto como porcentaje de la variación neta; comprobar si la suma de valores absolutos supera la variación neta; registrar el resultado en una tabla ordenada por magnitud.

In [27]:
# ===== EJERCICIO 1 =====
# Identificamos y ponderamos el efecto dominante de la descomposición.
## Comparamos Volumen, Mezcla y Precio según el tamaño de su contribución.
## Usamos el valor absoluto porque queremos medir la magnitud del efecto sin importar si es positivo o negativo.

efectos = pl.DataFrame({
    "efecto": ["Volumen", "Mezcla", "Precio"],  ## Creamos una columna con el nombre de cada efecto
    "contribucion": [efecto_volumen, efecto_mezcla, efecto_precio],  ## Guardamos la contribución calculada de cada efecto
}).with_columns(
    pl.col("contribucion").abs().alias("magnitud"),  ## Convertimos cada contribución a valor absoluto para comparar su tamaño
    (100 * pl.col("contribucion") / variacion_total).alias("pct_de_variacion_neta"),  ## Calculamos qué porcentaje representa cada efecto respecto a la variación neta
).sort("magnitud", descending=True)  ## Ordenamos los efectos desde el de mayor hasta el de menor magnitud


# Mostramos la tabla de efectos ordenada por magnitud.
## Esto permite identificar visualmente cuál es el efecto dominante.
## Redondeamos las cifras para que el resultado sea más fácil de leer.

print(efectos.select(
    "efecto",  ## Mostramos el nombre del efecto
    pl.col("contribucion").round(2),  ## Mostramos la contribución con dos decimales
    pl.col("magnitud").round(2),  ## Mostramos la magnitud absoluta con dos decimales
    pl.col("pct_de_variacion_neta").round(1),  ## Mostramos el porcentaje respecto a la variación neta con un decimal
))


# Identificamos el efecto que ocupa la primera posición después de ordenar.
## Como la tabla está ordenada de mayor a menor magnitud, la primera fila corresponde al efecto dominante.

dominante = efectos.row(0, named=True)  ## Extraemos toda la información del efecto dominante
suma_abs = efectos["magnitud"].sum()  ## Sumamos las magnitudes absolutas de Volumen, Mezcla y Precio


# Mostramos los resultados principales de la priorización.
## Comprobamos cuál es el efecto dominante, cuánto aporta y qué relación existe entre las magnitudes y la variación neta.

print(f"\nEfecto dominante        : {dominante['efecto']}")  ## Mostramos el nombre del efecto con mayor magnitud
print(f"Contribucion            : £ {dominante['contribucion']:,.2f}")  ## Mostramos cuánto contribuye el efecto dominante
print(f"Representa              : {dominante['pct_de_variacion_neta']:,.1f} % de la variacion neta")  ## Mostramos su peso respecto a la variación neta

print(f"\nSuma de magnitudes      : £ {suma_abs:,.2f}")  ## Mostramos la suma de los valores absolutos de los tres efectos
print(f"Variacion neta          : £ {variacion_total:,.2f}")  ## Mostramos la variación neta final
print(f"Razon suma/neta         : {suma_abs / abs(variacion_total):.2f} veces")  ## Calculamos cuántas veces la suma de magnitudes supera a la variación neta
print("Se compensan entre si   :", "SI" if suma_abs > abs(variacion_total) else "NO")  ## Verificamos si existen efectos positivos y negativos que se compensan

shape: (3, 4)
┌─────────┬──────────────┬────────────┬───────────────────────┐
│ efecto  ┆ contribucion ┆ magnitud   ┆ pct_de_variacion_neta │
│ ---     ┆ ---          ┆ ---        ┆ ---                   │
│ str     ┆ f64          ┆ f64        ┆ f64                   │
╞═════════╪══════════════╪════════════╪═══════════════════════╡
│ Volumen ┆ -1568093.05  ┆ 1568093.05 ┆ -664.2                │
│ Mezcla  ┆ 577550.82    ┆ 577550.82  ┆ 244.6                 │
│ Precio  ┆ -115918.44   ┆ 115918.44  ┆ -49.1                 │
└─────────┴──────────────┴────────────┴───────────────────────┘

Efecto dominante        : Volumen
Contribucion            : £ -1,568,093.05
Representa              : -664.2 % de la variacion neta

Suma de magnitudes      : £ 2,261,562.31
Variacion neta          : £ 236,086.10
Razon suma/neta         : 9.58 veces
Se compensan entre si   : SI


### **Identificación del efecto dominante**

El efecto dominante es **Volumen**, con una contribución de **−£1,568,093.05** y una magnitud de **£1,568,093.05**, siendo el mayor de los tres efectos. Le siguen **Mezcla** con **£577,550.82** y **Precio** con **−£115,918.44**.

Respecto a la variación neta de **£236,086.10**, el efecto Volumen representa **−664.2%**, Mezcla **244.6%** y Precio **−49.1%**. Estos porcentajes no suman 100% porque existen efectos positivos y negativos que se compensan.

La suma de las magnitudes es **£2,261,562.31**, equivalente a **9.58 veces** la variación neta. Esto confirma que la variación final de los ingresos es el resultado de movimientos mucho mayores que se compensan entre sí.

En conclusión, **Volumen es el principal driver por magnitud**, pero la variación neta positiva de £236 mil oculta una fuerte caída por volumen que fue compensada principalmente por el efecto positivo de Mezcla.

### ✅ Pregunta de cierre — Ejercicio 1

**¿El efecto dominante explica por sí solo la variación neta observada? Justifique con las cifras.**

**No, y la pregunta encierra una trampa deliberada que conviene desarmar con cuidado.** El efecto dominante entre los tres del catálogo común es el **efecto volumen, con −£ 1 568 093.05**, que equivale al **−664.2 % de la variación neta de +£ 236 086.10**. Un porcentaje de esa naturaleza —negativo y seis veces superior a 100— es la señal inequívoca de que **la lectura habitual del efecto dominante no aplica aquí**.

La lectura habitual —«el efecto dominante explica la mayor parte del cambio»— presupone que todos los efectos empujan en la misma dirección, de modo que cada uno es una fracción del total. Cuando los efectos se compensan, esa aritmética se rompe: la suma de magnitudes de los tres efectos asciende a **£ 2 261 562.31**, es decir, **9.58 veces la variación neta**. Sumando también las altas y bajas de catálogo, el movimiento bruto llega a **£ 5 012 823.39**, **21.2 veces** el resultado neto.

**Lo que las cifras sí permiten afirmar:**

1. El efecto volumen es el mayor movimiento adverso del catálogo común: **−£ 1.57 millones**.
2. La mezcla amortigua **+£ 0.58 millones** y el precio agrega **−£ 0.12 millones**, de modo que el catálogo común cierra en **−£ 1 106 460.66**, un **−12.73 %** respecto de sus £ 8 692 285.14 en P0.
3. La variación neta positiva **no proviene del catálogo común**: proviene íntegramente del recambio de referencias, cuyo saldo es **+£ 1 342 546.76** (£ 2 046 903.92 de altas menos £ 704 357.16 de bajas).

**Lo que las cifras no permiten afirmar:** que el volumen «explique» el resultado del año. Un neto pequeño construido con movimientos brutos veintiuna veces mayores es un **equilibrio inestable**, no una situación estable. Si el año siguiente las referencias nuevas dejaran de crecer al ritmo de su primer año, no habría nada que compense la pérdida de volumen del surtido histórico. **Ese es el verdadero mensaje del ejercicio y el que debe llegar al comité.**

---

## Ejercicio 2 — Aplicación de la descomposición a un mercado específico

**Se solicita:** identificar el país con mayor caída en libras excluyendo el Reino Unido; delimitar sus transacciones en ambos periodos; replicar la descomposición volumen-mezcla-precio sobre el catálogo común de ese mercado; comprobar la reconciliación.

In [28]:
# ===== EJERCICIO 2 =====
# Identificamos el mercado con la mayor caída absoluta, excluyendo al Reino Unido.
## Ordenamos los países por su variación de ingresos de menor a mayor.
## El primer registro será el país con la caída más grande en libras.

objetivo = (por_pais
            .filter(pl.col("pais") != "United Kingdom")  ## Excluimos Reino Unido porque el ejercicio pide analizar otro mercado
            .sort("variacion")  ## Ordenamos de la mayor caída a la mayor subida
            .row(0, named=True))  ## Seleccionamos el primer país y lo convertimos en un registro

PAIS = objetivo["pais"]  ## Guardamos el nombre del mercado seleccionado

print(f"Mercado seleccionado: {PAIS}")  ## Mostramos el país elegido
print(f"  P0: £ {objetivo['P0']:,.2f}   P1: £ {objetivo['P1']:,.2f}")  ## Mostramos sus ingresos en ambos periodos
print(f"  Variacion: £ {objetivo['variacion']:,.2f} ({objetivo['variacion_pct']:.2f} %)\n")  ## Mostramos la caída absoluta y porcentual


# Filtramos las transacciones del mercado seleccionado.
## Trabajamos únicamente con las operaciones de ese país para replicar la descomposición a nivel de mercado.

sub = comparables.filter(pl.col("pais") == PAIS)  ## Conservamos solo las transacciones correspondientes al país seleccionado


# Calculamos cantidades e ingresos por producto y periodo.
## Agrupamos por periodo y código de producto para obtener las unidades y el ingreso de cada referencia.
## El precio efectivo se calcula como ingreso dividido entre cantidad.

por_producto_pais = (
    sub.group_by(["periodo", "codigo"])
       .agg(
           pl.col("cantidad").sum().alias("q"),  ## Sumamos las unidades vendidas de cada producto
           pl.col("ingreso").sum().alias("r")  ## Sumamos el ingreso generado por cada producto
       )
       .with_columns(
           (pl.col("r") / pl.col("q")).alias("p")  ## Calculamos el precio efectivo promedio de cada producto
       )
)


# Separamos los productos de P0 y P1.
## Necesitamos comparar las mismas referencias entre ambos periodos.

a0 = por_producto_pais.filter(pl.col("periodo") == "P0").drop("periodo")  ## Extraemos los productos vendidos en P0
a1 = por_producto_pais.filter(pl.col("periodo") == "P1").drop("periodo")  ## Extraemos los productos vendidos en P1


# Clasificamos las referencias según su presencia en ambos periodos.
## Los productos comunes permiten realizar la descomposición volumen-mezcla-precio.
## Los discontinuados solo aparecen en P0 y los nuevos solo aparecen en P1.

comun_pais = a0.join(a1, on="codigo", suffix="_1")  ## Conservamos productos presentes tanto en P0 como en P1
disc_pais = a0.join(a1, on="codigo", how="anti")  ## Identificamos productos que estaban en P0 pero desaparecen en P1
nuev_pais = a1.join(a0, on="codigo", how="anti")  ## Identificamos productos que aparecen en P1 pero no estaban en P0


# Calculamos las unidades totales del catálogo común.
## QA0 representa las unidades de los productos comunes en P0.
## QA1 representa las unidades de los mismos productos comunes en P1.

QA0, QA1 = comun_pais["q"].sum(), comun_pais["q_1"].sum()  ## Sumamos las cantidades del catálogo común en ambos periodos


# Calculamos la participación de cada producto dentro del volumen total del catálogo común.
## s0 corresponde a la participación del producto en P0.
## s1 corresponde a la participación del producto en P1.
## Estas participaciones permiten medir el cambio de mezcla entre los productos.

cp = comun_pais.with_columns(
    (pl.col("q") / QA0).alias("s0"),  ## Calculamos la participación del producto en el volumen de P0
    (pl.col("q_1") / QA1).alias("s1")  ## Calculamos la participación del producto en el volumen de P1
)


# Calculamos los tres efectos de la descomposición volumen-mezcla-precio.
## Volumen mide el impacto de vender más o menos unidades manteniendo la estructura inicial.
## Mezcla mide el impacto de cambiar la participación relativa de los productos.
## Precio mide el impacto del cambio en el precio efectivo de los productos.

vol_pais = (QA1 - QA0) * (cp["s0"] * cp["p"]).sum()  ## Calculamos el efecto volumen del catálogo común

mez_pais = QA1 * ((cp["s1"] - cp["s0"]) * cp["p"]).sum()  ## Calculamos el efecto mezcla debido al cambio en la composición de ventas

pre_pais = QA1 * (cp["s1"] * (cp["p_1"] - cp["p"])).sum()  ## Calculamos el efecto precio debido al cambio de precio efectivo


# Calculamos las variaciones que utilizaremos para comprobar la reconciliación.
## La variación común compara únicamente los productos presentes en ambos periodos.
## La variación total incluye además los productos nuevos y discontinuados.

var_comun_pais = cp["r_1"].sum() - cp["r"].sum()  ## Calculamos el cambio de ingresos del catálogo común

var_total_pais = a1["r"].sum() - a0["r"].sum()  ## Calculamos el cambio total de ingresos del país


# Mostramos la composición del catálogo del mercado seleccionado.
## Esto permite conocer cuántos productos son comunes, nuevos y discontinuados.

print(f"Catalogo comun  : {comun_pais.height:>4} productos")  ## Mostramos la cantidad de productos presentes en ambos periodos
print(f"Discontinuados  : {disc_pais.height:>4} productos   £ {disc_pais['r'].sum():>12,.2f}")  ## Mostramos productos que desaparecieron y sus ingresos de P0
print(f"Nuevos en P1    : {nuev_pais.height:>4} productos   £ {nuev_pais['r'].sum():>12,.2f}\n")  ## Mostramos productos nuevos y sus ingresos de P1


# Mostramos los tres efectos calculados para el catálogo común.
## La suma de estos tres efectos debe coincidir exactamente con la variación del catálogo común.

print(f"Efecto volumen  : £ {vol_pais:>12,.2f}")  ## Mostramos cuánto aporta el cambio de volumen
print(f"Efecto mezcla   : £ {mez_pais:>12,.2f}")  ## Mostramos cuánto aporta el cambio de mezcla
print(f"Efecto precio   : £ {pre_pais:>12,.2f}")  ## Mostramos cuánto aporta el cambio de precio
print(f"{'-'*32}")  ## Dibujamos una línea para separar los efectos del resultado de reconciliación
print(f"Suma            : £ {vol_pais + mez_pais + pre_pais:>12,.2f}")  ## Sumamos los tres efectos
print(f"Variacion comun : £ {var_comun_pais:>12,.2f}")  ## Mostramos la variación real del catálogo común


# Verificamos que la descomposición volumen-mezcla-precio reconcilie.
## La diferencia permitida es menor a £0.01 debido a posibles diferencias de precisión decimal.

assert abs(var_comun_pais - (vol_pais + mez_pais + pre_pais)) < 0.01, "No reconcilia"  ## Comprobamos que los tres efectos expliquen exactamente la variación común


# Reconstruimos la variación total del mercado.
## Partimos de la variación del catálogo común y agregamos los productos nuevos y discontinuados.

reconstruida = var_comun_pais + nuev_pais["r"].sum() - disc_pais["r"].sum()  ## Construimos nuevamente la variación total incluyendo altas y bajas de productos

assert abs(var_total_pais - reconstruida) < 0.01, "El puente del pais no reconcilia"  ## Comprobamos que el puente completo del mercado también reconcilie


# Confirmamos que ambas reconciliaciones fueron correctas.
## Si alguno de los assert anteriores falla, Python detendrá la ejecución y mostrará el error.

print("\nReconciliacion verificada.")  ## Confirmamos que los cálculos son consistentes
print(f"Variacion total de {PAIS}: £ {var_total_pais:,.2f}")  ## Mostramos la variación total de ingresos del mercado

# Comparamos el volumen del catálogo común entre P0 y P1.
## Esto permite identificar si la cantidad de unidades vendidas de las referencias comunes aumentó o disminuyó.

print(f"  Unidades del catalogo comun: {QA0:,} -> {QA1:,} ({100*(QA1-QA0)/QA0:.2f} %)")  ## Mostramos las unidades iniciales, finales y su variación porcentual

Mercado seleccionado: EIRE
  P0: £ 352,563.30   P1: £ 263,709.97
  Variacion: £ -88,853.33 (-25.20 %)

Catalogo comun  : 1140 productos
Discontinuados  :  889 productos   £    74,313.01
Nuevos en P1    :  779 productos   £    81,175.57

Efecto volumen  : £   -94,481.17
Efecto mezcla   : £     7,550.65
Efecto precio   : £    -8,785.37
--------------------------------
Suma            : £   -95,715.89
Variacion comun : £   -95,715.89

Reconciliacion verificada.
Variacion total de EIRE: £ -88,853.33
  Unidades del catalogo comun: 153,934 -> 101,665 (-33.96 %)


### **Descomposición del mercado EIRE**

El mercado seleccionado es **EIRE**, porque presenta la mayor caída absoluta fuera del Reino Unido: pasa de **£352,563.30 en P0 a £263,709.97 en P1**, una disminución de **£88,853.33 (−25.20%)**.

En el catálogo común, el efecto dominante vuelve a ser **Volumen**, con **−£94,481.17**. El efecto Mezcla aporta **+£7,550.65**, mientras que Precio aporta **−£8,785.37**. La suma de los tres efectos es **−£95,715.89**, exactamente igual a la variación del catálogo común, por lo que la descomposición reconcilia correctamente.

El principal problema de EIRE está en el volumen: las unidades del catálogo común disminuyen de **153,934 a 101,665**, una caída de **33.96%**. Esto explica por qué el efecto volumen genera la mayor presión negativa sobre los ingresos del catálogo común.

Finalmente, el catálogo también tuvo **779 productos nuevos por £81,175.57** y **889 productos discontinuados por £74,313.01**. Estos cambios compensan parcialmente la caída del catálogo común y permiten llegar a la variación total de **−£88,853.33**.

En conclusión, **EIRE presenta una contracción importante explicada principalmente por la fuerte reducción del volumen de los productos comunes**. La reconciliación verificada confirma que la descomposición explica correctamente el movimiento de ingresos.

### ✅ Pregunta de cierre — Ejercicio 2

**¿Qué efecto explica la caída de ese mercado y en qué se diferencia del patrón del agregado?**

El mercado seleccionado es **EIRE (Irlanda)**, con una caída de **£ 88 853.33 (−25.20 %)**, la mayor en libras después del Reino Unido. La descomposición arroja:

| Componente | EIRE (£) | % de la variación total de EIRE |
|---|---:|---:|
| Efecto volumen | **−94 481.17** | 106.3 % |
| Efecto mezcla | +7 550.65 | −8.5 % |
| Efecto precio | −8 785.37 | 9.9 % |
| *Subtotal catálogo común (1 140 productos)* | *−95 715.89* | *107.7 %* |
| Productos nuevos (779 referencias) | +81 175.57 | −91.4 % |
| Productos discontinuados (889 referencias) | −74 313.01 | 83.6 % |
| **Variación total** | **−88 853.33** | 100 % |

**El efecto que explica la caída es, de manera abrumadora, el efecto volumen.** El catálogo común de EIRE pasa de **153 934 a 101 665 unidades**, una contracción del **−33.96 %**, casi el doble de severa que el −18.04 % del agregado. Valorizada al precio medio del periodo base, esa pérdida de unidades cuesta **£ 94 481**, cifra que por sí sola **supera** la caída total del mercado.

**Tres diferencias con el patrón agregado, y la tercera es la que decide:**

1. **La mezcla casi no actúa.** En el agregado, la mezcla aporta +£ 577 551, un amortiguador que compensa el 37 % de la caída de volumen. En EIRE aporta apenas +£ 7 551: el 8 % de su caída de volumen. El desplazamiento hacia productos de mayor valor unitario que se observa en el conjunto de la empresa **no ocurre en Irlanda**.
2. **El precio pesa relativamente más.** En el agregado el efecto precio representa el 7.4 % de la magnitud del efecto volumen; en EIRE, el 9.3 %. Es una diferencia menor, pero apunta en la misma dirección: en Irlanda se cobró algo menos por producto sin obtener a cambio ningún volumen adicional.
3. **La renovación de catálogo no compensa.** Esta es la diferencia decisiva. En el agregado, altas y bajas dejan un saldo neto de **+£ 1 342 547**, suficiente para convertir una caída de £ 1.11 millones en un crecimiento de £ 0.24 millones. En EIRE el saldo neto es de apenas **+£ 6 863** (£ 81 176 de altas contra £ 74 313 de bajas): las referencias nuevas entraron, pero **entraron exactamente para reemplazar a las que salieron, sin agregar negocio**.

**Conclusión en lenguaje de negocio.** El conjunto de la empresa perdió volumen en su surtido histórico y lo compensó vendiendo productos nuevos; Irlanda perdió volumen en su surtido histórico y **no lo compensó**. Sumado al hallazgo del Ejercicio 4 —que EIRE opera con solo tres clientes identificados— el diagnóstico se afina: no se trata de un mercado que se contrae, sino de **una o dos cuentas mayoristas que redujeron su nivel de pedidos en un tercio**. Las facturas pasan de 299 a 272 (−9 %) mientras el importe cae 25 %: los mismos clientes siguen comprando, pero compran menos en cada pedido. Esa es una conversación de gestión de cuentas clave, no una campaña de mercado.

---

## Ejercicio 3 — Comparación de la retención entre cohortes

**Se solicita:** extraer la retención del sexto mes de antigüedad de cada cohorte; excluir explícitamente las cohortes que no lo alcanzaron; ordenar cronológicamente y comparar; determinar si existe tendencia de mejora o de deterioro.

In [29]:
# ===== EJERCICIO 3 =====
# Comparamos la retención de las cohortes exactamente en el sexto mes de antigüedad.
## Primero identificamos qué cohortes ya tienen información suficiente para llegar al mes 6.
## Las cohortes que todavía no alcanzaron ese periodo se excluyen explícitamente.

CORTE = 6  ## Definimos el sexto mes como el punto de comparación entre cohortes


# Identificamos las cohortes que alcanzaron al menos 6 meses de antigüedad.
## Para cada cohorte buscamos su mayor antigüedad disponible.
## Si la antigüedad máxima es menor que 6, esa cohorte todavía no puede ser evaluada en el mes 6.

maduras = (retencion
           .group_by("cohorte")  ## Agrupamos los registros según el mes de nacimiento de la cohorte
           .agg(pl.col("antiguedad").max().alias("antiguedad_maxima"))  ## Obtenemos la máxima antigüedad disponible para cada cohorte
           .filter(pl.col("antiguedad_maxima") >= CORTE))  ## Conservamos únicamente las cohortes que alcanzaron el sexto mes


# Extraemos únicamente el registro correspondiente al sexto mes de cada cohorte madura.
## Así obtenemos una comparación homogénea: todas las cohortes se evalúan con exactamente 6 meses de antigüedad.

ret6 = (retencion
        .join(maduras, on="cohorte", how="inner")  ## Conservamos solamente las cohortes que alcanzaron el mes 6
        .filter(pl.col("antiguedad") == CORTE)  ## Seleccionamos exclusivamente el sexto mes de antigüedad
        .select(
            "cohorte",  ## Mostramos el mes en que nació cada cohorte
            pl.col("inicial").alias("clientes_iniciales"),  ## Mostramos cuántos clientes tenía inicialmente la cohorte
            pl.col("activos").alias("activos_mes_6"),  ## Mostramos cuántos clientes permanecen activos en el mes 6
            pl.col("tasa").round(1).alias("retencion_mes_6")  ## Mostramos la tasa de retención al sexto mes
        )
        .sort("cohorte"))  ## Ordenamos las cohortes cronológicamente


# Calculamos cuántas cohortes quedaron fuera del análisis.
## Una cohorte excluida no significa que tenga 0% de retención.
## Significa que todavía no existe información suficiente para medir su sexto mes.

excluidas = retencion["cohorte"].n_unique() - ret6.height  ## Restamos las cohortes evaluables del total de cohortes


# Mostramos el tamaño de la muestra utilizada en la comparación.
## Esto permite comprobar que las cohortes recientes fueron excluidas correctamente.

print(f"Cohortes totales                 : {retencion['cohorte'].n_unique()}")  ## Mostramos el número total de cohortes
print(f"Cohortes que alcanzaron el mes {CORTE} : {ret6.height}")  ## Mostramos cuántas cohortes tienen información del sexto mes
print(f"Cohortes excluidas (sin dato)    : {excluidas}\n")  ## Mostramos cuántas cohortes no pudieron ser evaluadas

print(ret6)  ## Mostramos la retención del sexto mes ordenada cronológicamente


# Dividimos las cohortes evaluables en dos grupos para comparar las más antiguas con las más recientes.
## La división permite observar si la retención está mejorando o deteriorándose a través del tiempo.

mitad = ret6.height // 2  ## Calculamos la mitad del número de cohortes disponibles

antigua = ret6.head(mitad)["retencion_mes_6"].mean()  ## Calculamos la retención promedio del sexto mes de las cohortes más antiguas
reciente = ret6.tail(ret6.height - mitad)["retencion_mes_6"].mean()  ## Calculamos la retención promedio del sexto mes de las cohortes más recientes


# Mostramos la comparación entre las cohortes antiguas y recientes.
## Una diferencia negativa indica que las cohortes recientes retienen menos clientes que las antiguas.

print(f"\nPromedio {mitad} cohortes mas antiguas : {antigua:.2f} %")  ## Mostramos el promedio de retención de las cohortes más antiguas
print(f"Promedio {ret6.height-mitad} cohortes mas recientes: {reciente:.2f} %")  ## Mostramos el promedio de retención de las cohortes más recientes
print(f"Diferencia                        : {reciente - antigua:+.2f} puntos porcentuales")  ## Calculamos el cambio entre ambos grupos


# Determinamos automáticamente si existe mejora o deterioro.
## Si la retención reciente es menor que la antigua, clasificamos el comportamiento como deterioro.

print("Tendencia                         :",
      "DETERIORO" if reciente < antigua else "MEJORA")  ## Indicamos la dirección de la tendencia observada


# Separamos las cohortes según el periodo en que nacieron.
## P0 corresponde a cohortes nacidas antes de diciembre de 2010.
## P1 corresponde a cohortes nacidas desde diciembre de 2010.

import datetime  ## Importamos datetime para poder comparar las fechas de las cohortes

g0 = ret6.filter(pl.col("cohorte") < datetime.date(2010, 12, 1))  ## Seleccionamos las cohortes nacidas durante P0
g1 = ret6.filter(pl.col("cohorte") >= datetime.date(2010, 12, 1))  ## Seleccionamos las cohortes nacidas durante P1


# Comparamos directamente la retención promedio del sexto mes entre P0 y P1.
## Esta comparación permite evaluar si las cohortes del segundo periodo presentan menor retención que las del primero.

print(f"\nCohortes nacidas en P0 ({g0.height}): {g0['retencion_mes_6'].mean():.2f} %")  ## Mostramos la retención promedio de las cohortes nacidas en P0
print(f"Cohortes nacidas en P1 ({g1.height}) : {g1['retencion_mes_6'].mean():.2f} %")  ## Mostramos la retención promedio de las cohortes nacidas en P1

Cohortes totales                 : 25
Cohortes que alcanzaron el mes 6 : 19
Cohortes excluidas (sin dato)    : 6

shape: (19, 4)
┌────────────┬────────────────────┬───────────────┬─────────────────┐
│ cohorte    ┆ clientes_iniciales ┆ activos_mes_6 ┆ retencion_mes_6 │
│ ---        ┆ ---                ┆ ---           ┆ ---             │
│ date       ┆ u32                ┆ u32           ┆ f64             │
╞════════════╪════════════════════╪═══════════════╪═════════════════╡
│ 2009-12-01 ┆ 951                ┆ 358           ┆ 37.6            │
│ 2010-01-01 ┆ 368                ┆ 99            ┆ 26.9            │
│ 2010-02-01 ┆ 375                ┆ 72            ┆ 19.2            │
│ 2010-03-01 ┆ 441                ┆ 109           ┆ 24.7            │
│ 2010-04-01 ┆ 294                ┆ 81            ┆ 27.6            │
│ 2010-05-01 ┆ 255                ┆ 54            ┆ 21.2            │
│ 2010-06-01 ┆ 267                ┆ 34            ┆ 12.7            │
│ 2010-07-01 ┆ 185             

### **Comparación de la retención entre cohortes**

De las **25 cohortes** disponibles, **19 alcanzaron el sexto mes de antigüedad** y **6 fueron excluidas** porque todavía no contaban con información suficiente. La retención al mes 6 presenta valores muy diferentes entre cohortes: la cohorte de diciembre de 2009 alcanza **37.6%**, mientras que agosto de 2010 registra solo **9.8%**.

Al comparar las **9 cohortes más antiguas** con las **10 más recientes**, la retención promedio disminuye de **21.23% a 14.94%**, una diferencia de **−6.29 puntos porcentuales**. Por ello, el código identifica una tendencia de **DETERIORO** en la retención.

La comparación por periodos confirma el resultado. Las **12 cohortes nacidas en P0** presentan una retención promedio al sexto mes de **19.24%**, mientras que las **7 cohortes nacidas en P1** alcanzan solo **15.66%**, una reducción de **3.58 puntos porcentuales**.

En conclusión, **sí existe evidencia descriptiva de deterioro de la retención al sexto mes**: las cohortes más recientes retienen menos clientes que las antiguas. Sin embargo, este resultado muestra una tendencia descriptiva y **no demuestra por sí solo la causa** del deterioro.

### ✅ Pregunta de cierre — Ejercicio 3

**¿Las cohortes recientes retienen mejor o peor que las antiguas? ¿Qué implicancia tiene para la captación?**

**Retienen peor, y el deterioro es consistente bajo los dos cortes que el código calcula.**

| Comparación | Cohortes antiguas | Cohortes recientes | Diferencia |
|---|---:|---:|---:|
| Mitad y mitad (9 contra 10 cohortes) | 21.23 % | 14.94 % | **−6.29 p.p.** |
| Por periodo de nacimiento (12 en P0, 7 en P1) | 19.24 % | 15.66 % | **−3.58 p.p.** |

De las 25 cohortes construidas, **19 alcanzaron el mes 6 y 6 quedaron excluidas** por no haberlo alcanzado. Esa exclusión no es un detalle administrativo: es la condición de validez de toda la comparación. Si las seis cohortes truncadas se hubieran incluido con retención cero, el promedio reciente habría caído por debajo del 12 % y se habría reportado un desplome que **no existe en los datos, sino en el método**.

El deterioro de 3.58 puntos porcentuales representa una pérdida relativa del **18.6 %** de la capacidad de retención a medio plazo. Traducido a clientes: de cada 100 captados, alrededor de 19 seguían comprando al sexto mes en el primer año, y solo unos 16 en el segundo.

**Tres precauciones de lectura que el estudiante debe registrar:**

1. **La cohorte de diciembre de 2009 (37.6 %) está censurada a la izquierda** y eleva el promedio antiguo. Es la primera del archivo y absorbe a clientes que ya compraban antes del inicio del registro; su «primera compra» es solo la primera observada. Excluyéndola, el promedio del primer año baja a aproximadamente 17.6 % y la brecha se reduce, aunque **no desaparece**.
2. **Las cohortes recientes son pequeñas** —76, 72, 106, 108, 111 clientes frente a 951, 441 o 375 en el primer año—, por lo que su tasa es más volátil. La cohorte de diciembre de 2010 retiene 5.3 % con apenas 4 clientes activos: bastarían tres personas más para duplicar esa cifra.
3. **La estacionalidad no está controlada.** El mes 6 de una cohorte de abril cae en octubre (temporada alta de regalos); el de una cohorte de junio cae en diciembre. Una comparación más rigurosa contrastaría cohortes del mismo mes calendario en años distintos: abril de 2010 (**27.6 %**) contra abril de 2011 (**17.9 %**), que confirma el deterioro con 9.7 puntos de diferencia y sin contaminación estacional.

**Implicancia para la captación —que es lo que la pregunta realmente pide.** La empresa **captó clientes de menor valor recurrente en el segundo año**. Esto tiene tres consecuencias operativas concretas:

- **El costo de adquisición se encarece en términos reales.** Si un cliente nuevo aporta menos ingreso de por vida, el mismo gasto de captación compra menos valor. Los datos lo confirman por otra vía: en P1 un cliente nuevo genera **£ 913.70** mientras uno recurrente genera **£ 2 502.51**, es decir, **2.74 veces más**.
- **El crecimiento por volumen de captación es insostenible.** Captar más clientes para compensar la peor retención es una carrera que se pierde: cada camada nueva se agota más rápido y obliga a captar aún más.
- **La prioridad de inversión debe reequilibrarse hacia la retención.** Con 2 708 clientes recurrentes generando el **82.4 %** de los ingresos identificados de P1 (£ 6.78 millones de £ 8.22 millones), un punto porcentual de mejora en retención vale más que un punto de aumento en captación. La acción concreta que se desprende: **auditar el canal de captación del segundo año** —qué mercados, qué campañas, qué productos de entrada— y comparar el comportamiento de los clientes que trajo cada uno.

---

## Ejercicio 4 — Consulta de mercados prioritarios con condiciones múltiples en DuckDB

**Se solicita:** construir una consulta SQL con `SELECT`, `GROUP BY`, `HAVING` y `ORDER BY`; calcular por país los ingresos de cada periodo, la variación absoluta y la cantidad de clientes distintos; conservar solo los mercados con variación negativa, ingresos de P0 sobre un umbral declarado y más de una cantidad mínima de clientes; ordenar por variación ascendente.

In [31]:
# ===== EJERCICIO 4 =====
UMBRAL_INGRESO  = 20_000
MINIMO_CLIENTES = 5

prioritarios = duckdb.sql(f"""
    SELECT  pais,
            ROUND(SUM(CASE WHEN periodo = 'P0' THEN ingreso ELSE 0 END), 2) AS p0,
            ROUND(SUM(CASE WHEN periodo = 'P1' THEN ingreso ELSE 0 END), 2) AS p1,
            ROUND(SUM(CASE WHEN periodo = 'P1' THEN ingreso ELSE -ingreso END), 2) AS variacion,
            ROUND(100 * SUM(CASE WHEN periodo = 'P1' THEN ingreso ELSE -ingreso END)
                      / SUM(CASE WHEN periodo = 'P0' THEN ingreso ELSE 0 END), 2) AS variacion_pct,
            COUNT(DISTINCT cliente_id) AS clientes
    FROM    comparables
    GROUP BY pais
    HAVING  SUM(CASE WHEN periodo = 'P1' THEN ingreso ELSE -ingreso END) < 0
      AND   SUM(CASE WHEN periodo = 'P0' THEN ingreso ELSE 0 END) > {UMBRAL_INGRESO}
      AND   COUNT(DISTINCT cliente_id) > {MINIMO_CLIENTES}
    ORDER BY variacion ASC
""").pl()

print(f"Criterios declarados:")
print(f"  1. variacion < 0")
print(f"  2. ingresos P0 > £ {UMBRAL_INGRESO:,}")
print(f"  3. clientes identificados > {MINIMO_CLIENTES}\n")
print(prioritarios)
print(f"\nMercados que cumplen los tres criterios: {prioritarios.height}")
if prioritarios.height:
    top = prioritarios.row(0, named=True)
    print(f"Encabeza el ordenamiento: {top['pais']} "
          f"(£ {top['variacion']:,.2f}, {top['variacion_pct']:.2f} %, {top['clientes']} clientes)")

descartados = duckdb.sql(f"""
    SELECT  pais,
            ROUND(SUM(CASE WHEN periodo = 'P1' THEN ingreso ELSE -ingreso END), 2) AS variacion,
            COUNT(DISTINCT cliente_id) AS clientes
    FROM    comparables GROUP BY pais
    HAVING  SUM(CASE WHEN periodo = 'P1' THEN ingreso ELSE -ingreso END) < 0
      AND   SUM(CASE WHEN periodo = 'P0' THEN ingreso ELSE 0 END) > {UMBRAL_INGRESO}
      AND   COUNT(DISTINCT cliente_id) <= {MINIMO_CLIENTES}
    ORDER BY variacion ASC
""").pl()
print("\nMercados grandes descartados por concentracion de clientes:")
print(descartados)

Criterios declarados:
  1. variacion < 0
  2. ingresos P0 > £ 20,000
  3. clientes identificados > 5

shape: (3, 6)
┌─────────────────┬──────────┬──────────┬───────────┬───────────────┬──────────┐
│ pais            ┆ p0       ┆ p1       ┆ variacion ┆ variacion_pct ┆ clientes │
│ ---             ┆ ---      ┆ ---      ┆ ---       ┆ ---           ┆ ---      │
│ str             ┆ f64      ┆ f64      ┆ f64       ┆ f64           ┆ i64      │
╞═════════════════╪══════════╪══════════╪═══════════╪═══════════════╪══════════╡
│ Denmark         ┆ 49211.35 ┆ 18060.44 ┆ -31150.91 ┆ -63.3         ┆ 11       │
│ Sweden          ┆ 49490.31 ┆ 36590.83 ┆ -12899.48 ┆ -26.06        ┆ 19       │
│ Channel Islands ┆ 24032.79 ┆ 19799.14 ┆ -4233.65  ┆ -17.62        ┆ 13       │
└─────────────────┴──────────┴──────────┴───────────┴───────────────┴──────────┘

Mercados que cumplen los tres criterios: 3
Encabeza el ordenamiento: Denmark (£ -31,150.91, -63.30 %, 11 clientes)

Mercados grandes descartados por conce

### **Mercados prioritarios según condiciones múltiples**

La consulta seleccionó **3 mercados prioritarios** que cumplen simultáneamente los tres criterios: presentar una variación negativa, superar **£20,000 de ingresos en P0** y tener **más de 5 clientes identificados**. Los mercados son **Dinamarca, Suecia y Channel Islands**.

**Dinamarca** encabeza el ordenamiento con una caída de **−£31,150.91 (−63.30%)** y **11 clientes**. Le sigue **Suecia**, con **−£12,899.48 (−26.06%)** y **19 clientes**, y finalmente **Channel Islands**, con **−£4,233.65 (−17.62%)** y **13 clientes**.

Un resultado importante es que **EIRE queda descartado**, a pesar de tener la mayor caída absoluta de todos los mercados con **−£88,853.33**, porque solo tiene **3 clientes identificados** y la consulta exige más de 5. Esto demuestra que el criterio de clientes cambia la priorización: EIRE aparece como un problema de concentración de cuentas, mientras que Dinamarca, Suecia y Channel Islands cumplen las condiciones para ser considerados problemas de mercado.

En conclusión, bajo estos criterios, **Dinamarca es el mercado prioritario**, porque combina una caída significativa en libras y porcentaje con una cantidad de clientes suficiente para justificar un análisis de mercado.

### ✅ Pregunta de cierre — Ejercicio 4

**¿Cuántos mercados satisfacen los tres criterios y cuál encabeza el ordenamiento? ¿Coincide con el de mayor caída porcentual?**

**Con los umbrales declarados —variación negativa, ingresos de P0 superiores a £ 20 000 y más de 5 clientes identificados— solo tres mercados sobreviven al filtro:**

| Orden | Mercado | P0 (£) | P1 (£) | Variación (£) | Variación (%) | Clientes |
|---:|---|---:|---:|---:|---:|---:|
| 1 | **Dinamarca** | 49 211.35 | 18 060.44 | **−31 150.91** | −63.30 % | 11 |
| 2 | Suecia | 49 490.31 | 36 590.83 | −12 899.48 | −26.06 % | 19 |
| 3 | Islas del Canal | 24 032.79 | 19 799.14 | −4 233.65 | −17.62 % | 13 |

**Encabeza el ordenamiento Dinamarca**, y el resultado más instructivo del ejercicio es **quién quedó fuera**: de los 43 mercados del conjunto, el filtro elimina a 40. Entre ellos:

- **EIRE queda excluido por el tercer criterio**, pese a ser la mayor caída en libras de todo el conjunto (−£ 88 853.33). La consulta cuenta **3 clientes identificados**, por debajo del mínimo de 5. El filtro funciona exactamente como fue diseñado: **separa el deterioro de un mercado de la pérdida de una cuenta.** Una caída de £ 88 853 concentrada en tres compradores no es un problema de plaza; es una conversación con dos o tres clientes.
- **Los cinco mercados que cayeron −100 %** —Tailandia, Nigeria, Corea, Indias Occidentales y Bermudas— quedan excluidos por el segundo criterio: entre los cinco movían £ 6 091.17 en P0, muy por debajo del umbral de £ 20 000.
- **Emiratos Árabes Unidos y Grecia**, con las mayores caídas porcentuales entre los mercados que siguen operando (−77.82 % y −72.84 %), quedan fuera por la misma razón: £ 8 408 y £ 14 286 de base.

**¿Coincide con el de mayor caída porcentual? No, y esa es la respuesta sustantiva de la pregunta.** La mayor caída porcentual absoluta es de −100 % y corresponde a cinco mercados irrelevantes en importe. Dinamarca es, sin embargo, **el mercado que combina las tres condiciones**: pierde dinero significativo, lo pierde con gravedad (−63.30 %, casi dos tercios de su facturación) y lo pierde en once cuentas distintas, lo que descarta que se trate del comportamiento de un solo comprador.

**La lección metodológica del ejercicio.** La cláusula `HAVING` no es un tecnicismo de SQL: **es donde el analista escribe la política de la empresa**. Cada umbral —£ 20 000, 5 clientes— es una decisión de negocio que debe declararse y defenderse, no un número arbitrario. Con umbrales distintos el resultado cambia: si el mínimo de clientes bajara a 2, EIRE encabezaría la lista y la recomendación sería otra. Por eso el código los define como constantes con nombre (`UMBRAL_INGRESO`, `MINIMO_CLIENTES`) y los imprime antes del resultado: **un filtro no declarado es un sesgo escondido.**

---

## Ejercicio 5 — Representación conjunta de la magnitud y la intensidad del deterioro

**Se solicita:** construir con Plotly un gráfico de dispersión con la variación en libras en el eje horizontal y la variación porcentual en el vertical; representar los ingresos de P0 mediante el tamaño del marcador; identificar cada punto con el nombre del país y excluir el Reino Unido; rotular ejes y título de modo que el gráfico se interprete sin recurrir al código.

In [34]:
# ===== EJERCICIO 5 =====
# Construimos un gráfico de dispersión para representar conjuntamente la magnitud y la intensidad del deterioro.
## El eje X muestra la variación absoluta en libras.
## El eje Y muestra la variación porcentual respecto de P0.
## El tamaño de cada punto representa los ingresos del mercado en P0.


# Preparamos los datos que utilizaremos en el gráfico.
## Excluimos Reino Unido porque su tamaño es muy superior al resto de mercados.
## También eliminamos mercados sin ingresos en P0 para evitar problemas al representar el tamaño de los puntos.

mapa = (por_pais
        .filter((pl.col("pais") != "United Kingdom") & (pl.col("P0") > 0))  ## Excluimos UK y mercados con P0 igual a cero
        .with_columns(pl.col("variacion_pct").round(1))  ## Redondeamos la variación porcentual a un decimal
        .to_pandas())  ## Convertimos el DataFrame de Polars a pandas para utilizar Plotly Express


# Creamos el gráfico de dispersión.
## Cada punto representa un país.
## Su posición muestra la variación absoluta y porcentual.
## El tamaño permite comparar el tamaño económico de cada mercado.

figura = px.scatter(
    mapa,
    x="variacion",  ## Eje X: variación absoluta de ingresos entre P1 y P0
    y="variacion_pct",  ## Eje Y: variación porcentual respecto de P0
    size="P0",  ## El tamaño del punto representa los ingresos del periodo P0
    text="pais",  ## Mostramos el nombre del país junto a cada punto
    size_max=55,  ## Limitamos el tamaño máximo de los marcadores
    color="variacion_pct",  ## Utilizamos la variación porcentual para diferenciar visualmente los mercados
    color_continuous_scale="RdYlGn",  ## Aplicamos una escala de color que diferencia caídas y crecimientos
    labels={
        "variacion": "Variación absoluta de ingresos P1 − P0 (£)",  ## Etiquetamos claramente el eje horizontal
        "variacion_pct": "Variación relativa respecto de P0 (%)",  ## Etiquetamos claramente el eje vertical
        "P0": "Ingresos P0 (£)",  ## Indicamos qué representa el tamaño del punto
        "variacion_pct_": "%"  ## Definimos una etiqueta adicional para la variable porcentual
    },
)


# Ajustamos las etiquetas y las líneas de referencia.
## Las líneas en cero permiten separar visualmente los mercados que crecen de los que caen.

figura.update_traces(
    textposition="top center",  ## Colocamos el nombre del país encima de cada punto
    textfont_size=9  ## Ajustamos el tamaño de las etiquetas para mejorar la legibilidad
)

figura.add_hline(
    y=0,
    line_dash="dot",
    line_color="#9AA7B4"
)  ## Añadimos una línea horizontal en 0% para separar crecimiento y caída porcentual

figura.add_vline(
    x=0,
    line_dash="dot",
    line_color="#9AA7B4"
)  ## Añadimos una línea vertical en £0 para separar pérdidas y ganancias absolutas


# Configuramos el título y la presentación general del gráfico.
## El subtítulo explica cómo interpretar el tamaño de los puntos y el cuadrante de mayor interés comercial.

figura.update_layout(
    title="Magnitud e intensidad del deterioro por mercado (excluido el Reino Unido)<br>"
          "<sup>El tamaño del punto representa los ingresos del periodo base. "
          "Cuadrante inferior izquierdo = prioridad comercial.</sup>",  ## Explicamos el objetivo del gráfico directamente en el título

    height=620,  ## Definimos la altura del gráfico
    showlegend=False,  ## Ocultamos la leyenda porque cada punto ya está identificado por el país
    coloraxis_showscale=False,  ## Ocultamos la escala de colores para reducir elementos visuales innecesarios
)


# Mostramos el gráfico interactivo.
## El gráfico permite localizar rápidamente los mercados con pérdidas absolutas y porcentuales.

figura.show()


# Identificamos los mercados ubicados en el cuadrante inferior izquierdo.
## Estos mercados presentan simultáneamente una caída en libras y una caída porcentual.
## Son especialmente relevantes para analizar porque combinan magnitud e intensidad del deterioro.

print("Cuadrante inferior izquierdo (caen en libras y en porcentaje):")  ## Mostramos el título del listado

print(
    por_pais
    .filter(
        (pl.col("pais") != "United Kingdom") &
        (pl.col("variacion") < 0)
    )  ## Conservamos mercados distintos de UK que presentan una variación absoluta negativa
    .select(
        "pais",  ## Mostramos el nombre del mercado
        pl.col("P0").round(2),  ## Mostramos sus ingresos de P0
        pl.col("variacion").round(2),  ## Mostramos la pérdida absoluta en libras
        pl.col("variacion_pct").round(2)  ## Mostramos la pérdida porcentual
    )
    .sort("variacion")  ## Ordenamos desde la mayor pérdida absoluta
    .head(8)  ## Mostramos los ocho mercados con mayor caída
)

Cuadrante inferior izquierdo (caen en libras y en porcentaje):
shape: (8, 4)
┌──────────────────────┬──────────┬───────────┬───────────────┐
│ pais                 ┆ P0       ┆ variacion ┆ variacion_pct │
│ ---                  ┆ ---      ┆ ---       ┆ ---           │
│ str                  ┆ f64      ┆ f64       ┆ f64           │
╞══════════════════════╪══════════╪═══════════╪═══════════════╡
│ EIRE                 ┆ 352563.3 ┆ -88853.33 ┆ -25.2         │
│ Denmark              ┆ 49211.35 ┆ -31150.91 ┆ -63.3         │
│ Sweden               ┆ 49490.31 ┆ -12899.48 ┆ -26.06        │
│ Greece               ┆ 14285.67 ┆ -10406.14 ┆ -72.84        │
│ United Arab Emirates ┆ 8408.45  ┆ -6543.67  ┆ -77.82        │
│ Channel Islands      ┆ 24032.79 ┆ -4233.65  ┆ -17.62        │
│ Austria              ┆ 11554.33 ┆ -3334.85  ┆ -28.86        │
│ Thailand             ┆ 3070.54  ┆ -3070.54  ┆ -100          │
└──────────────────────┴──────────┴───────────┴───────────────┘


### **Mercados del cuadrante inferior izquierdo**

El resultado identifica **8 mercados** que presentan simultáneamente una caída absoluta de ingresos y una caída porcentual. **EIRE** registra la mayor pérdida absoluta, con **−£88,853.33 (−25.20%)**, seguido de **Dinamarca**, con **−£31,150.91 (−63.30%)**, y **Suecia**, con **−£12,899.48 (−26.06%)**.

En términos porcentuales, las caídas más intensas corresponden a **Tailandia (−100%)**, **Emiratos Árabes Unidos (−77.82%)** y **Grecia (−72.84%)**. Sin embargo, sus pérdidas absolutas son mucho menores que las de EIRE y Dinamarca, por lo que el porcentaje por sí solo no determina la prioridad.

El gráfico también muestra esta diferencia mediante el tamaño de los puntos: **EIRE tiene una base P0 de £352,563.30**, mientras que Tailandia tenía solo **£3,070.54**. Por ello, una caída del 100% en Tailandia representa un impacto económico mucho menor que la caída de EIRE.

En conclusión, el cuadrante inferior izquierdo permite localizar los mercados que **caen tanto en importe como en porcentaje**, pero para priorizar acciones comerciales debemos considerar conjuntamente **magnitud de la pérdida, intensidad porcentual y tamaño del mercado**.

### ✅ Pregunta de cierre — Ejercicio 5

**¿Qué mercado presenta simultáneamente caída elevada en libras y en porcentaje? ¿Por qué constituye una prioridad distinta de un mercado con gran caída absoluta pero deterioro relativo moderado?**

**El mercado que cae con fuerza en ambas dimensiones es Dinamarca: −£ 31 150.91 y −63.30 %.** Es el único punto del gráfico que se ubica simultáneamente muy a la izquierda (importe) y muy abajo (intensidad) conservando un tamaño de marcador apreciable, es decir, una base de negocio que justifica actuar.

El gráfico organiza los 42 mercados —excluido el Reino Unido— en cuatro cuadrantes de lectura distinta:

| Ubicación en el gráfico | Mercados | Lectura | Acción que corresponde |
|---|---|---|---|
| Abajo a la izquierda, punto grande | **Dinamarca** (−£ 31 151, −63.30 %, 11 clientes) | Mercado que se está perdiendo de verdad | **Intervención comercial de mercado.** Diagnóstico de campo: competencia local, portes, plazos, distribuidor. |
| Izquierda extrema, cerca del eje horizontal | **EIRE** (−£ 88 853, −25.20 %, 3 clientes) | Mucho dinero, deterioro moderado, altísima concentración | **Gestión de cuentas clave.** Llamada del director comercial. Barato y de alta probabilidad de recuperación. |
| Abajo a la derecha, puntos diminutos | Emiratos (−77.82 %), Grecia (−72.84 %), Tailandia (−100 %), Bahréin, Nigeria | Porcentajes dramáticos sobre bases minúsculas | **Registrar y no actuar.** Entre todos no llegan a £ 25 000. |
| Arriba a la derecha, puntos crecientes | Australia (+£ 108 408, +365 %), Japón (+£ 31 809, +567 %), Noruega (+£ 23 588, +385 %), Francia (+£ 51 357, +41 %) | Mercados en expansión | **Consolidar.** Verificar que el crecimiento no dependa de una sola cuenta antes de invertir. |

**Por qué Dinamarca y EIRE son prioridades de naturaleza distinta —el núcleo de la pregunta.**

Son dos problemas que exigen dos respuestas organizativas diferentes, y confundirlos lleva a gastar el recurso equivocado:

1. **La naturaleza del problema difiere.** EIRE pierde el 25 % de su facturación repartida entre **3 clientes identificados**: basta con que una cuenta mayorista haya reducido pedidos para explicar los £ 88 853. Dinamarca pierde el 63 % repartido entre **11 clientes**: que once cuentas se contraigan a la vez en dos tercios no se explica por una decisión individual, sino por algo que cambió en la plaza.
2. **La probabilidad de recuperación difiere.** Un cliente que reduce pedidos pero sigue comprando —EIRE mantiene 272 facturas frente a 299— **sigue siendo cliente**, y recuperar volumen con quien ya compra es la operación comercial más barata que existe. Un mercado que perdió dos tercios de su facturación puede haber cambiado de proveedor, y recuperarlo exige una oferta nueva, no una llamada.
3. **El riesgo de no actuar difiere.** En EIRE el riesgo está acotado y es visible: si la cuenta se pierde del todo, se pierden los £ 263 710 restantes, pero se sabrá de inmediato. En Dinamarca el riesgo es de contagio: si el motivo del retroceso es un competidor nórdico, lo mismo puede estar empezando en Suecia —que ya cae 26.06 %— y en Noruega. **El caso danés es un caso de aprendizaje sobre una región; el irlandés es un caso de gestión sobre una cuenta.**
4. **El costo de la acción difiere.** Reactivar tres cuentas irlandesas es una tarea de días para el equipo existente. Diagnosticar y recuperar un mercado nórdico es un proyecto de meses con presupuesto propio. Ante recursos limitados, la secuencia racional es **hacer primero lo barato y luego lo caro**, pero asignar el recurso escaso —el analista, el presupuesto de investigación de mercado— al caso danés.

> **Por qué el gráfico de dispersión resuelve un problema que las dos listas ordenadas no resolvían.** La lista por libras pone a EIRE primero y esconde a Dinamarca en segundo lugar. La lista por porcentaje pone a Nigeria primero —£ 112.57 de pérdida— y a Dinamarca en noveno. Ninguna de las dos, leída por separado, lleva a la decisión correcta. **El gráfico muestra las dos dimensiones a la vez y añade una tercera —el tamaño del mercado— en el área del marcador**, de modo que el ojo distingue de inmediato un mercado grande que se deteriora de uno diminuto que se evapora. Es un ejemplo directo del principio de Knaflic: la representación adecuada no adorna el análisis, **lo completa**.

---

# **Del diagnóstico a la decisión**

## ✅ Respuesta modelo a la pregunta de decisión

### 1. El driver de mayor contribución absoluta y la cifra que lo sustenta

**El driver de mayor contribución absoluta es la renovación del catálogo, con +£ 2 046 903.92 aportados por 674 referencias nuevas**, equivalentes al **40.8 %** de la suma de magnitudes de los cinco componentes del puente y al **21.25 %** de los ingresos totales de P1.

Ese driver, sin embargo, **no debe reportarse solo**, porque aislado induce a la lectura optimista que el laboratorio busca desmontar. La formulación correcta para el comité es la siguiente:

> «Los ingresos crecieron £ 236 086 (+2.51 %). Ese crecimiento **no proviene del negocio existente**. El catálogo que la empresa ya vendía perdió £ 1 106 461, un −12.73 %, arrastrado por una caída de volumen de £ 1 568 093 sobre 925 411 unidades menos (−18.04 %). El resultado positivo se explica íntegramente por el recambio de referencias: £ 2 046 904 de altas contra £ 704 357 de bajas, saldo neto **+£ 1 342 547**. Sin esa renovación, el año habría cerrado con una caída de más de un millón de libras.»

Los dos drivers que conviene llevar en una sola lámina, porque juntos cuentan la historia completa:

| Driver | Cifra | Qué significa |
|---|---:|---|
| **Volumen del catálogo común** | **−£ 1 568 093.05** | El negocio histórico se contrae. Es el problema. |
| **Productos nuevos** | **+£ 2 046 903.92** | La renovación lo tapa. Es la muleta, no la cura. |

### 2. La acción empresarial que se recomienda

Se recomienda un plan de tres acciones, **ordenadas por relación entre impacto y costo**, cada una con su cifra de sustento y su indicador de verificación:

**Acción 1 — Auditar los 990 productos discontinuados antes de dar de baja una sola referencia más.** *(Prioridad alta, costo bajo, plazo inmediato.)*

Los productos retirados movían **£ 704 357.16** y **496 903 unidades** en P0, a un precio medio de **£ 1.42** por unidad. Los que entraron se venden a **£ 1.96** por unidad. El recambio desplazó el catálogo hacia arriba en valor unitario, lo que es favorable en ingreso, pero **el análisis no dispone del costo unitario y por tanto no puede afirmar que sea favorable en margen**. La auditoría debe responder tres preguntas que el dato actual no responde: ¿cada baja fue una decisión comercial o una rotura de stock no gestionada? ¿el margen de las referencias nuevas compensa el de las retiradas? ¿cuántos de los clientes que dejaron de comprar lo hicieron tras la desaparición de una referencia que representaba más de la mitad de su cesta? *Indicador de verificación: porcentaje de bajas con motivo documentado, hoy desconocido.*

**Acción 2 — Recuperar volumen del catálogo común, empezando por las referencias de mayor caída en unidades.** *(Prioridad alta, costo medio, plazo un trimestre.)*

La pérdida de **925 411 unidades** en el surtido histórico es el mayor movimiento adverso del año y el único que no tiene contrapartida. Mientras no se revierta, el crecimiento dependerá de mantener indefinidamente el ritmo de altas de catálogo, lo que ninguna empresa sostiene. *Indicador de verificación: variación del ingreso a catálogo constante, hoy en **−12.73 %**; objetivo mínimo para el próximo periodo: **0 %**.*

**Acción 3 — Intervenir Dinamarca como caso de mercado y EIRE como caso de cuenta, con equipos y presupuestos distintos.** *(Prioridad media, costo bajo en EIRE y alto en Dinamarca.)*

EIRE concentra **£ 88 853** de caída en **3 clientes identificados** que siguen comprando (272 facturas frente a 299): es gestión de cuentas clave y se resuelve con una llamada del director comercial. Dinamarca pierde **63.30 %** repartido entre **11 clientes**, un patrón que sugiere un cambio estructural de la plaza y que además podría estar empezando en Suecia (−26.06 %). *Indicador de verificación: recuperación del importe medio por factura en EIRE; ingreso trimestral de Dinamarca y Suecia.*

**Acción 4 — Reequilibrar la inversión hacia la retención.** *(Prioridad media, costo bajo, plazo permanente.)*

La retención al mes 6 cayó de **19.24 %** a **15.66 %**, un deterioro relativo del 18.6 %. Un cliente recurrente genera **£ 2 502.51** contra **£ 913.70** de uno nuevo: **2.74 veces más**. Con 2 708 recurrentes aportando el **82.4 %** de los ingresos identificados de P1, cada punto de retención recuperado vale más que un punto de captación adicional. *Indicador de verificación: retención al mes 6 de las cohortes que se vayan cumpliendo, medida siempre a igual antigüedad.*

### 3. La limitación del análisis: qué NO demuestra este trabajo

**Este análisis reconcilia exactamente y, aun así, no demuestra ninguna causa.** La reconciliación prueba que la aritmética es correcta y completa, no que los factores identificados hayan producido el resultado. Las ocho limitaciones que deben constar por escrito en el informe son:

1. **No demuestra causalidad.** El puente es una identidad contable. Que el volumen explique £ 1.57 millones no significa que «la caída de volumen causó» nada: es el nombre que se le da a una porción de la aritmética.
2. **No resuelve la dirección de la relación con las discontinuaciones.** ¿Se retiraron los productos porque se vendían poco, o se vendieron poco porque se retiraron? El dato es idéntico bajo ambas hipótesis.
3. **No distingue demanda de disponibilidad.** No hay información de stock. La caída de 925 411 unidades puede ser enteramente un problema de abastecimiento, y en ese caso toda recomendación comercial sería la respuesta equivocada al problema correcto.
4. **No mide margen.** Todo el análisis es de ingreso. Un recambio de catálogo hacia productos más caros puede ser rentable o ruinoso según su costo, y el conjunto no contiene costos.
5. **No cubre al 22.77 % de las líneas en el análisis de clientes.** Las cohortes describen a los 5 852 clientes identificados; las conclusiones sobre retención no se extienden automáticamente al total de compradores.
6. **Depende de las reglas de calidad declaradas.** Cuatro reglas descartaron 64 031 filas (6.00 %). Reglas distintas —por ejemplo, restar las cancelaciones en lugar de excluirlas— producirían cifras distintas sin que nadie se haya equivocado.
7. **Depende de la descomposición elegida.** La secuencia volumen → mezcla → precio reparte los términos de interacción de un modo determinado. Bennet, Fisher o Törnqvist repartirían distinto y también reconciliarían.
8. **No incorpora contexto externo.** No hay competencia, macroeconomía, tipo de cambio ni estacionalidad modelada. El periodo 2010-2011 corresponde además a la salida de la crisis financiera y a una recesión en Irlanda, factores que el dato no observa y que ninguna conclusión puede ignorar sin decirlo.

> **Frase de cierre recomendada para la sustentación.** «Este análisis identifica **dónde** está el movimiento y **cuánto** vale cada componente, con reconciliación exacta y trazabilidad verificable de la fuente. **No identifica por qué ocurrió.** Para eso se requiere incorporar stock, costos, calendario de decisiones de catálogo y canal de captación, y en última instancia un diseño experimental. Hasta entonces, las recomendaciones son hipótesis priorizadas por evidencia, no conclusiones causales.»

---

# **Ticket de salida**

### ✅ Ticket 1 — ¿Por qué pueden subir los ingresos mientras caen las unidades?

Porque el ingreso no es una función solo de las unidades. Partiendo de la identidad $R = Q\cdot\bar{p}$, donde $\bar{p}=\sum_i s_i p_i$ es el precio medio ponderado, el ingreso puede subir con $Q$ cayendo siempre que $\bar{p}$ suba lo suficiente para compensar. Y $\bar{p}$ puede subir por dos vías completamente distintas: porque suben los precios individuales $p_i$ (efecto precio) o porque cambia la composición $s_i$ hacia productos más caros (efecto mezcla). **Confundir ambas vías es el error que este laboratorio combate**, porque conducen a decisiones opuestas: una sugiere revisar la política de precios, la otra revisar el surtido.

En el caso concreto, los tres efectos actuaron así sobre el catálogo común:

- **Efecto volumen: −£ 1 568 093.05.** Se vendieron 925 411 unidades menos (−18.04 %). Valorizadas al precio medio de P0 (£ 1.694483), esa pérdida costó £ 1.57 millones. **Empuja el ingreso hacia abajo y es el mayor movimiento adverso del año.**
- **Efecto mezcla: +£ 577 550.82.** La composición se desplazó hacia productos de mayor precio unitario: con la mezcla de P1 y los precios de P0, el precio medio habría sido £ 1.831853 en lugar de £ 1.694483, es decir, **+£ 0.13737 por unidad**. **Empuja hacia arriba.**
- **Efecto precio: −£ 115 918.44.** Los precios efectivos, en promedio, bajaron £ 0.027571 por unidad. **Empuja hacia abajo, y desmiente la hipótesis de que el ticket subió por precios.**

A esos tres se suma el recambio de catálogo: **+£ 2 046 903.92** de referencias nuevas contra **−£ 704 357.16** de referencias retiradas. **El saldo neto de todo es +£ 236 086.10.**

**Respuesta en una frase:** los ingresos subieron **a pesar** de vender menos unidades, porque la empresa vendió una composición de productos más cara y renovó su catálogo con referencias de mayor valor unitario; **no porque subiera los precios, que de hecho bajaron.**

### ✅ Ticket 2 — ¿Qué variable debe mantenerse constante para que la comparación entre dos cohortes sea válida?

**La antigüedad**, es decir, el número de meses transcurridos desde la primera compra ($k$), **no el mes calendario**.

Dos cohortes solo pueden compararse en la misma columna $k$ de la matriz, y únicamente si ambas **efectivamente vivieron** ese mes. Comparar el mes 6 de una cohorte con el mes 2 de otra mezcla dos fenómenos distintos: la maduración natural del cliente y el efecto del calendario. Y comparar contra una celda vacía es peor todavía, porque esa celda significa *aún no observado* y no *abandonaron*: en este laboratorio, 6 de las 25 cohortes no alcanzaron el mes 6 y deben excluirse explícitamente, tal como hace el Ejercicio 3.

Dos exigencias adicionales que un análisis riguroso añade a la principal: **la definición de «activo» debe ser la misma** para ambas cohortes (aquí, al menos una compra en el mes), y **el denominador debe ser siempre el tamaño inicial de la cohorte**, nunca el del mes anterior, porque en ese caso las tasas dejarían de ser comparables entre sí.

### ✅ Ticket 3 — Driver dominante, cifra que lo sustenta y limitación

**Driver dominante:** la **renovación del catálogo**, con **+£ 2 046 903.92** de las 674 referencias nuevas, es el componente de mayor magnitud absoluta (40.8 % del movimiento bruto). Su contrapeso, y el verdadero problema del año, es el **efecto volumen del catálogo común: −£ 1 568 093.05**.

**Cifra que lo sustenta:** el catálogo común cayó **−£ 1 106 460.66 (−12.73 %)** y el saldo del recambio de referencias fue **+£ 1 342 546.76**. La diferencia entre ambos es exactamente la variación neta observada: **+£ 236 086.10**, con reconciliación verificada a **£ 0.00** de diferencia.

**Limitación:** el análisis **no demuestra causalidad**. Reconcilia, localiza y cuantifica, pero no dispone de stock, costos, motivo de cada discontinuación, canal de captación ni grupo de control. No puede descartarse que la caída de volumen provenga de rotura de stock ni que las discontinuaciones sean consecuencia —y no causa— de la menor demanda. Además, las cohortes describen únicamente a los 5 852 clientes identificados, el 77.23 % de las líneas.

---

# **Ticket de salida**

### ✅ Ticket 1 — ¿Por qué pueden subir los ingresos mientras caen las unidades?

Los ingresos pueden subir aunque se vendan menos unidades porque también depende del precio medio de los productos vendidos. Este precio puede aumentar por un cambio en los precios o porque se venden más productos de mayor precio. A esto último se le conoce como efecto mezcla.

En nuestro caso, las unidades del catálogo común bajaron **925,411 (−18.04 %)** y el efecto volumen fue de **−£1,568,093.05**. En cambio, el efecto mezcla fue positivo, con **+£577,550.82**, porque la composición de productos vendidos cambió hacia productos de mayor precio. El efecto precio fue negativo, **−£115,918.44**, por lo que los ingresos no aumentaron por una subida general de precios.

Además, los productos nuevos aportaron **+£2,046,903.92**, mientras que los productos discontinuados restaron **−£704,357.16**. Finalmente, los ingresos aumentaron **£236,086.10 (+2.51 %)**.

En resumen, aunque se vendieron menos unidades, el cambio en la mezcla de productos y principalmente las nuevas referencias compensaron la caída del volumen.

### ✅ Ticket 2 — ¿Qué variable debe mantenerse constante para que la comparación entre dos cohortes sea válida?

La variable que debe mantenerse constante es la **antigüedad de la cohorte**, es decir, los meses que han pasado desde la primera compra del cliente.

Por ejemplo, para comparar dos cohortes correctamente debemos comparar su mes 1 con el mes 1 de la otra cohorte, su mes 2 con el mes 2, y así sucesivamente. No sería correcto comparar el mes 6 de una cohorte con el mes 2 de otra porque los clientes tienen diferente tiempo desde su primera compra.

También debemos utilizar la misma definición de cliente activo y el mismo denominador. En nuestro análisis, un cliente es activo si realizó al menos una compra durante el mes y la retención se calcula tomando como referencia el tamaño inicial de la cohorte.

Las celdas vacías tampoco significan que la retención sea 0 %. Significan que la cohorte todavía no ha llegado a esa antigüedad. Por eso, en el análisis del mes 6 se excluyeron las cohortes que todavía no tenían seis meses de observación.

### ✅ Ticket 3 — Driver dominante, cifra que lo sustenta y limitación

En el puente completo, el componente con mayor magnitud fue **Productos nuevos**, con **+£2,046,903.92** de 674 referencias nuevas. Sin embargo, si consideramos solamente los efectos de volumen, mezcla y precio, el principal fue **volumen**, con **−£1,568,093.05**.

El catálogo común disminuyó **−£1,106,460.66 (−12.73 %)**, mientras que el recambio de productos tuvo un saldo positivo de **+£1,342,546.76**. Al compensarse estos movimientos, la variación total terminó siendo de **+£236,086.10** y la reconciliación fue de **£0.00**.

La principal limitación es que este análisis **no demuestra causalidad**. Podemos saber cuánto aportó cada componente a la variación, pero no exactamente por qué ocurrió. Por ejemplo, no tenemos información suficiente sobre stock, costos o motivos de discontinuación para saber si la caída de volumen se debió a menor demanda o a problemas de disponibilidad.

Además, el análisis de cohortes considera a los **5,852 clientes identificados**, por lo que sus resultados de retención no se pueden aplicar automáticamente a todas las líneas del dataset.